namespace Kanawanagasaki.BlazorContracts.SourceGenerator;

using Microsoft.CodeAnalysis;
using System.Collections.Immutable;
using System.IO;
using System.Linq;

[Generator]
public class ClientContractsServiceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var config = context.AnalyzerConfigOptionsProvider.Select((options, _) =>
        {
            options.GlobalOptions.TryGetValue("build_property.BlazorContracts", out var value);
            return value;
        });

        var compilation = context.CompilationProvider.Select((compilation, ct) =>
        {
            var attributeSymb = compilation.GetTypeByMetadataName(Constants.ContractAttributeFullName);
            if (attributeSymb is null)
                return ImmutableArray<ContractMetadata>.Empty;

            var metadataList = new List<ContractMetadata>();
            foreach (var assembly in compilation.SourceModule.ReferencedAssemblySymbols.Concat([compilation.Assembly]))
            {
                if (ct.IsCancellationRequested)
                    return ImmutableArray<ContractMetadata>.Empty;

                if (Helper.IsFrameworkAssembly(assembly.ToDisplayString(Helper.SYMB_DISPLAY_FORMAT)))
                    continue;

                foreach (var type in Helper.GetAllTypes(assembly.GlobalNamespace, ct))
                {
                    if (type.GetAttributes().Any(x => SymbolEqualityComparer.Default.Equals(x.AttributeClass, attributeSymb))
                        && ContractMetadata.TryCreate(type, out var metadata)
                        && metadata is not null)
                    {
                        metadataList.Add(metadata);
                    }
                }
            }

            return metadataList.ToImmutableArray();
        });

        var combined = config.Combine(compilation);

        context.RegisterSourceOutput(combined, Execute);
    }

    private void Execute(SourceProductionContext context, (string?, ImmutableArray<ContractMetadata>) tuple)
    {
        var (config, list) = tuple;
        var optIns = config?.ToLowerInvariant().Split(',') ?? [];
        if (!optIns.Contains("clientservice"))
            return;

        using var sw = new StringWriter();
        using var iw = new IndentedTextWriter(sw);
        iw.WriteLine("""
            // <auto-generated/>
            #nullable enable
            namespace Kanawanagasaki.BlazorContracts.Client;

            using System.Linq;

            public class ClientContractsService : Kanawanagasaki.BlazorContracts.Client.ClientContractsServiceBase, Kanawanagasaki.BlazorContracts.IContractsService
            {
                public ClientContractsService(Microsoft.AspNetCore.Components.NavigationManager navMgr)
                    : base(CreateHttpClient(navMgr), CreateJsonOptions())
                {
                }

                public ClientContractsService(System.Net.Http.HttpClient http)
                    : base(http, CreateJsonOptions())
                {
                }

                public ClientContractsService(System.Net.Http.HttpClient http, System.Text.Json.JsonSerializerOptions jsonOptions)
                    : base(http, jsonOptions)
                {
                }

                private static System.Net.Http.HttpClient CreateHttpClient(Microsoft.AspNetCore.Components.NavigationManager navMgr)
                {
                    var http = new System.Net.Http.HttpClient();
                    http.BaseAddress = new System.Uri(navMgr.BaseUri);
                    return http;
                }

                private static System.Text.Json.JsonSerializerOptions CreateJsonOptions()
                {
                    return new System.Text.Json.JsonSerializerOptions
                    {
                        PropertyNamingPolicy = null,
                        DictionaryKeyPolicy = null,
                        DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull,
                        TypeInfoResolver = new System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver
                        {
                            Modifiers =
                            {
                                typeInfo =>
                                {
            """);

        foreach (var contract in list)
        {
            if (contract.IsMessagePack)
                continue;
            if (!contract.HasBinaryProperty)
                continue;

            iw.IndentLevel = 6;
            iw.WriteLine($"if(typeInfo.Type == typeof({contract.FullyQualifiedName}))");
            iw.WriteLine("{");

            iw.IndentLevel++;
            foreach (var prop in contract.Properties.Values)
            {
                if (prop.IsByteArray || prop.IsContractFile)
                    iw.WriteLine($$"""
                        var contractProperty{{prop.Name}} = typeInfo.Properties.FirstOrDefault(property =>
                            property.Name == nameof({{contract.FullyQualifiedName}}.{{prop.Name}})
                            || (property.AttributeProvider is System.Reflection.PropertyInfo contractClrProperty{{prop.Name}} && contractClrProperty{{prop.Name}}.Name == nameof({{contract.FullyQualifiedName}}.{{prop.Name}})));
                        if (contractProperty{{prop.Name}} is not null)
                            typeInfo.Properties.Remove(contractProperty{{prop.Name}});
                        """);
            }

            iw.DecreaseAndWriteLine("}");
        }

        iw.IndentLevel = 0;
        iw.WriteLine($$"""
                                    if(typeInfo.Type == typeof(Kanawanagasaki.BlazorContracts.ContractResult<byte[]>))
                                    {
                                        var dataProperty = typeInfo.Properties.FirstOrDefault(property =>
                                            property.Name == nameof(Kanawanagasaki.BlazorContracts.ContractResult<byte[]>.Data)
                                            || (property.AttributeProvider is System.Reflection.PropertyInfo dataClrProperty && dataClrProperty.Name == nameof(Kanawanagasaki.BlazorContracts.ContractResult<byte[]>.Data)));
                                        if (dataProperty is not null)
                                            typeInfo.Properties.Remove(dataProperty);
                                    }
                                    if(typeInfo.Type == typeof(Kanawanagasaki.BlazorContracts.ContractResult<{{typeof(Stream).FullName}}>))
                                    {
                                        var streamDataProperty = typeInfo.Properties.FirstOrDefault(property =>
                                            property.Name == nameof(Kanawanagasaki.BlazorContracts.ContractResult<{{typeof(Stream).FullName}}>.Data)
                                            || (property.AttributeProvider is System.Reflection.PropertyInfo streamDataClrProperty && streamDataClrProperty.Name == nameof(Kanawanagasaki.BlazorContracts.ContractResult<{{typeof(Stream).FullName}}>.Data)));
                                        if (streamDataProperty is not null)
                                            typeInfo.Properties.Remove(streamDataProperty);
                                    }
                                }
                            }
                        }
                    };
                }
            """);

        iw.IndentLevel = 1;
        foreach (var metadata in list)
        {
            iw.WriteLine();

            if (metadata.IsDisposableReturnType)
                iw.WriteLine($"public async Task<{Constants.DisposableContractResultFullName}<{metadata.ReturnFullyQualifiedName}>> ProcessAsync({metadata.FullyQualifiedName} contract, System.Threading.CancellationToken ct = default)");
            else if (metadata.IsReturning)
                iw.WriteLine($"public async Task<{Constants.ContractResultFullName}<{metadata.ReturnFullyQualifiedName}>> ProcessAsync({metadata.FullyQualifiedName} contract, System.Threading.CancellationToken ct = default)");
            else
                iw.WriteLine($"public async Task<{Constants.ContractResultFullName}> ProcessAsync({metadata.FullyQualifiedName} contract, System.Threading.CancellationToken ct = default)");
            iw.WriteLineAndIncrease("{");

            var endpoint = metadata.Endpoint;
            var routeParts = endpoint.Split(['/', '\\'], StringSplitOptions.RemoveEmptyEntries)
                                     .Where(x => 2 < x.Length && x[0] == '{' && x[x.Length - 1] == '}')
                                     .Select(x => x.Substring(1, x.Length - 2))
                                     .ToArray();

            foreach (var routePart in routeParts)
            {
                var routeToString = metadata.Properties.TryGetValue(routePart, out var routeProp)
                    ? routeProp.FormatToString($"contract.{routePart}")
                    : $"contract.{routePart}.ToString()";
                endpoint = endpoint.Replace($"{{{routePart}}}", $"{{System.Uri.EscapeDataString({routeToString})}}");
            }

            var hasQuery = false;
            if (metadata.VerbStr == "Get" || metadata.VerbStr == "Delete")
            {
                var query = metadata.Properties.ToDictionary(x => x.Key, x => x.Value);
                foreach (var routePart in routeParts)
                    query.Remove(routePart);

                if (0 < query.Count)
                {
                    iw.WriteLine("var query = new System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, string?>>();");
                    foreach (var kv in query)
                    {
                        var queryKey = (kv.Value.JsonPropertyName ?? kv.Key).Replace("\\", "\\\\").Replace("\"", "\\\"");
                        if (kv.Value.IsReferenceType)
                        {
                            iw.WriteLine($"if (contract.{kv.Key} is not null)");
                            iw.IncreaseAndWriteLine($"query.Add(new(\"{queryKey}\", {kv.Value.FormatToString($"contract.{kv.Key}")}));");
                        }
                        else if (kv.Value.IsNullable)
                        {
                            iw.WriteLine($"if (contract.{kv.Key}.HasValue)");
                            iw.IncreaseAndWriteLine($"query.Add(new(\"{queryKey}\", {kv.Value.FormatToString($"contract.{kv.Key}.Value")}));");
                        }
                        else
                        {
                            iw.WriteLine($"if (!System.Collections.Generic.EqualityComparer<{kv.Value.FullyQualifiedName}>.Default.Equals(contract.{kv.Key}, default))");
                            iw.IncreaseAndWriteLine($"query.Add(new(\"{queryKey}\", {kv.Value.FormatToString($"contract.{kv.Key}")}));");
                        }
                        iw.IndentLevel--;
                    }
                    hasQuery = true;
                }
            }
            iw.WriteLine($$"""
                var method = System.Net.Http.HttpMethod.{{metadata.VerbStr}};
                var endpoint = {{(hasQuery ? $"Microsoft.AspNetCore.WebUtilities.QueryHelpers.AddQueryString($\"{endpoint}\", query)" : $"$\"{endpoint}\"")}};

                using var request = new System.Net.Http.HttpRequestMessage(method, endpoint);

                """);

            if (metadata.VerbStr == "Post" || metadata.VerbStr == "Put")
            {
                GenerateRequestBody(iw, metadata);
            }

            if (metadata.IsStreamReturnType)
                iw.WriteLine("return await ProcessStreamCoreAsync(request, ct);");
            else if (metadata.IsByteArrayReturnType)
                iw.WriteLine("return await ProcessBytesCoreAsync(request, ct);");
            else if (metadata.IsDisposableReturnType)
                iw.WriteLine($"return await ProcessDisposableCoreAsync<{metadata.ReturnFullyQualifiedName}>(request, ct);");
            else if (metadata.IsReturning)
                iw.WriteLine($"return await ProcessCoreAsync<{metadata.ReturnFullyQualifiedName}>(request, ct);");
            else
                iw.WriteLine("return await ProcessCoreAsync(request, ct);");

            iw.DecreaseAndWriteLine("}");
        }

        iw.DecreaseAndWriteLine("}");

        context.AddSource("ClientContractsService.g.cs", sw.ToString());
    }

    private static void GenerateRequestBody(IndentedTextWriter iw, ContractMetadata metadata)
    {
        var isMessagePack = metadata.IsMessagePack;
        var hasContractFile = metadata.HasContractFileProperty;
        var hasJsonBinary = !isMessagePack && metadata.HasBinaryProperty;
        var level = metadata.IsCompressed ? $", {metadata.CompressionLevelSource}" : string.Empty;

        if (isMessagePack && hasContractFile)
        {
            iw.WriteLine($$"""
                using var content = new System.Net.Http.MultipartFormDataContent();
                content.Add(Kanawanagasaki.BlazorContracts.ContractBody.CreateMessagePack(contract{{level}}), "{{metadata.Name}}", "{{metadata.Name}}.msgpack");
                """);

            foreach (var prop in metadata.Properties.Values)
            {
                if (prop.IsContractFile)
                {
                    iw.WriteLine($$"""
                        if (contract.{{prop.Name}} is not null)
                        {
                            content.Add(Kanawanagasaki.BlazorContracts.ContractBody.CreateFile(contract.{{prop.Name}}{{level}}), "{{prop.Name}}", contract.{{prop.Name}}.FileName);
                        }
                        """);
                }
            }
        }
        else if (isMessagePack)
        {
            iw.WriteLine($$"""
                using var content = Kanawanagasaki.BlazorContracts.ContractBody.CreateMessagePack(contract{{level}});
                """);
        }
        else if (hasJsonBinary)
        {
            iw.WriteLine($$"""
                using var content = new System.Net.Http.MultipartFormDataContent();
                content.Add(Kanawanagasaki.BlazorContracts.ContractBody.CreateJson(contract, _jsonOptions{{level}}), "{{metadata.Name}}");
                """);

            foreach (var prop in metadata.Properties.Values)
            {
                if (prop.IsByteArray)
                {
                    iw.WriteLine($$"""
                        if (contract.{{prop.Name}} is not null)
                        {
                            content.Add(Kanawanagasaki.BlazorContracts.ContractBody.CreateBinary(contract.{{prop.Name}}, Kanawanagasaki.BlazorContracts.ContractMediaTypes.Binary{{level}}), "{{prop.Name}}", "{{prop.Name}}.bin");
                        }
                        """);
                }
                else if (prop.IsContractFile)
                {
                    iw.WriteLine($$"""
                        if (contract.{{prop.Name}} is not null)
                        {
                            content.Add(Kanawanagasaki.BlazorContracts.ContractBody.CreateFile(contract.{{prop.Name}}{{level}}), "{{prop.Name}}", contract.{{prop.Name}}.FileName);
                        }
                        """);
                }
            }
        }
        else
        {
            iw.WriteLine($$"""
                using var content = Kanawanagasaki.BlazorContracts.ContractBody.CreateJson(contract, _jsonOptions{{level}});
                """);
        }

        iw.WriteLine("request.Content = content;");
        iw.WriteLine();
    }
}
