namespace Kanawanagasaki.BlazorContracts.SourceGenerator;

using Kanawanagasaki.BlazorContracts.SourceGenerator;
using Microsoft.CodeAnalysis;
using System.Collections.Immutable;
using System.Diagnostics.Contracts;
using System.IO;
using System.Linq;

[Generator]
public class ClientContractsServiceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var config = context.AnalyzerConfigOptionsProvider.Select((options, _) =>
        {
            options.GlobalOptions.TryGetValue("build_property.BlazorContracts", out var value);
            return value;
        });

        var compilation = context.CompilationProvider.Select((compilation, ct) =>
        {
            var attributeSymb = compilation.GetTypeByMetadataName(Constants.ContractAttributeFullName);
            if (attributeSymb is null)
                return ImmutableArray<ContractMetadata>.Empty;

            var metadataList = new List<ContractMetadata>();
            foreach (var assembly in compilation.SourceModule.ReferencedAssemblySymbols.Concat([compilation.Assembly]))
            {
                if (ct.IsCancellationRequested)
                    return ImmutableArray<ContractMetadata>.Empty;

                if (Helper.IsFrameworkAssembly(assembly.ToDisplayString(Helper.SYMB_DISPLAY_FORMAT)))
                    continue;

                foreach (var type in Helper.GetAllTypes(assembly.GlobalNamespace, ct))
                {
                    if (type.GetAttributes().Any(x => SymbolEqualityComparer.Default.Equals(x.AttributeClass, attributeSymb))
                        && ContractMetadata.TryCreate(type, out var metadata)
                        && metadata is not null)
                    {
                        metadataList.Add(metadata);
                    }
                }
            }

            return metadataList.ToImmutableArray();
        });

        var combined = config.Combine(compilation);

        context.RegisterSourceOutput(combined, Execute);
    }

    private void Execute(SourceProductionContext context, (string?, ImmutableArray<ContractMetadata>) tuple)
    {
        var (config, list) = tuple;
        var optIns = config?.ToLowerInvariant().Split(',') ?? [];
        if (!optIns.Contains("clientservice"))
            return;

        using var sw = new StringWriter();
        using var iw = new IndentedTextWriter(sw);
        iw.WriteLine("""
            // <auto-generated/>
            namespace Kanawanagasaki.BlazorContracts.Client;

            using System.Linq;

            public class ClientContractsService : Kanawanagasaki.BlazorContracts.IContractsService
            {
                private readonly System.Net.Http.HttpClient _http;
                private readonly System.Text.Json.JsonSerializerOptions _jsonOptions;

                public ClientContractsService(Microsoft.AspNetCore.Components.NavigationManager navMgr)
                {
                    this._http = new System.Net.Http.HttpClient();
                    this._http.BaseAddress = new System.Uri(navMgr.BaseUri);
                    this._jsonOptions = new System.Text.Json.JsonSerializerOptions
                    {
                        PropertyNamingPolicy = null,
                        DictionaryKeyPolicy = null,
                        DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull,
                        TypeInfoResolver = new System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver
                        {
                            Modifiers =
                            {
                                __typeInfo =>
                                {
            """);

        foreach (var contract in list)
        {
            if (!contract.Properties.Values.Any(x => x.IsByteArray || x.IsContractFile))
                continue;

            iw.IndentLevel = 6;
            iw.WriteLine($"if(__typeInfo.Type == typeof({contract.FullyQualifiedName}))");
            iw.WriteLine("{");

            iw.IndentLevel++;
            foreach (var prop in contract.Properties.Values)
            {
                if (prop.IsByteArray || prop.IsContractFile)
                    iw.WriteLine($"__typeInfo.Properties.Remove(__typeInfo.Properties.First(__x => __x.Name == nameof({contract.FullyQualifiedName}.{prop.Name})));");
            }

            iw.DecreaseAndWriteLine("}");
        }

        iw.IndentLevel = 0;
        iw.WriteLine($$"""
                                    if(__typeInfo.Type == typeof(Kanawanagasaki.BlazorContracts.ContractResult<byte[]>))
                                    {
                                        __typeInfo.Properties.Remove(__typeInfo.Properties.First(__x => __x.Name == nameof(Kanawanagasaki.BlazorContracts.ContractResult<byte[]>.Data)));
                                    }
                                    if(__typeInfo.Type == typeof(Kanawanagasaki.BlazorContracts.ContractResult<{{typeof(Stream).FullName}}>))
                                    {
                                        __typeInfo.Properties.Remove(__typeInfo.Properties.First(__x => __x.Name == nameof(Kanawanagasaki.BlazorContracts.ContractResult<{{typeof(Stream).FullName}}>.Data)));
                                    }
                                }
                            }
                        }
                    };
                }
            """);

        iw.IndentLevel = 1;
        foreach (var metadata in list)
        {
            iw.WriteLine();

            if (metadata.IsDisposableReturnType)
                iw.WriteLine($"public async Task<{Constants.DisposableContractResultFullName}<{metadata.ReturnFullyQualifiedName}>> ProcessAsync({metadata.FullyQualifiedName} contract, System.Threading.CancellationToken ct = default)");
            else if (metadata.IsReturning)
                iw.WriteLine($"public async Task<{Constants.ContractResultFullName}<{metadata.ReturnFullyQualifiedName}>> ProcessAsync({metadata.FullyQualifiedName} contract, System.Threading.CancellationToken ct = default)");
            else
                iw.WriteLine($"public async Task<{Constants.ContractResultFullName}> ProcessAsync({metadata.FullyQualifiedName} contract, System.Threading.CancellationToken ct = default)");
            iw.WriteLineAndIncrease("{");

            iw.WriteLine("try");
            iw.WriteLineAndIncrease("{");

            var endpoint = metadata.Endpoint;
            var routeParts = endpoint.Split(['/', '\\'], StringSplitOptions.RemoveEmptyEntries)
                                     .Where(x => 2 < x.Length && x[0] == '{' && x[x.Length - 1] == '}')
                                     .Select(x => x.Substring(1, x.Length - 2))
                                     .ToArray();

            foreach (var routePart in routeParts)
                endpoint = endpoint.Replace($"{{{routePart}}}", $"{{System.Web.HttpUtility.UrlEncode(contract.{routePart}.ToString())}}");

            var hasQuery = false;
            if (metadata.VerbStr == "Get" || metadata.VerbStr == "Delete")
            {
                var query = metadata.Properties.ToDictionary(x => x.Key, x => x.Value);
                foreach (var routePart in routeParts)
                    query.Remove(routePart);

                if (0 < query.Count)
                {
                    iw.WriteLine("var query = System.Web.HttpUtility.ParseQueryString(string.Empty);");
                    foreach (var kv in query)
                    {
                        if (kv.Value.IsReferenceType || kv.Value.IsNullable)
                        {
                            if (kv.Value.IsReferenceType)
                            {
                                iw.WriteLine($"if (contract.{kv.Key} is not null)");
                                iw.IncreaseAndWriteLine($"query[\"{kv.Key}\"] = contract.{kv.Key}.ToString();");
                            }
                            else
                            {
                                iw.WriteLine($"if (contract.{kv.Key}.HasValue)");
                                iw.IncreaseAndWriteLine($"query[\"{kv.Key}\"] = contract.{kv.Key}.Value.ToString();");
                            }
                            iw.IndentLevel--;
                        }
                        else
                            iw.WriteLine($"query[\"{kv.Key}\"] = contract.{kv.Key}.ToString();");
                    }
                    hasQuery = true;
                }
            }
            iw.WriteLine($$"""
                var method = System.Net.Http.HttpMethod.{{metadata.VerbStr}};
                var endpoint = $"{{endpoint}}"{{(hasQuery ? " + \"?\" + query" : "")}};

                using var request = new System.Net.Http.HttpRequestMessage(method, endpoint);

                """);

            if (metadata.VerbStr == "Post" || metadata.VerbStr == "Put")
            {
                if (metadata.Properties.Values.Any(x => x.IsByteArray || x.IsContractFile))
                {
                    iw.WriteLine($"""
                        using var content = new System.Net.Http.MultipartFormDataContent();
                        var multipartJson = System.Text.Json.JsonSerializer.Serialize(contract, _jsonOptions);
                        content.Add(new System.Net.Http.StringContent(multipartJson, System.Text.Encoding.UTF8, "application/json"), "{metadata.Name}");
                        """);

                    foreach (var prop in metadata.Properties.Values)
                    {
                        if (prop.IsByteArray)
                        {
                            iw.WriteLine($$"""
                                if (contract.{{prop.Name}} is not null)
                                {
                                    var byteArrContent = new System.Net.Http.ByteArrayContent(contract.{{prop.Name}});
                                    byteArrContent.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/octet-stream");
                                    content.Add(byteArrContent, "{{prop.Name}}", "{{prop.Name}}.bin");
                                }
                                """);
                        }
                        else if (prop.IsContractFile)
                        {
                            iw.WriteLine($$"""
                                if (contract.{{prop.Name}} is not null)
                                {
                                    var streamContent = new System.Net.Http.StreamContent(contract.{{prop.Name}}.Stream);
                                    streamContent.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue(contract.{{prop.Name}}.MediaType);
                                    content.Add(streamContent, "{{prop.Name}}", contract.{{prop.Name}}.FileName);
                                }
                                """);
                        }
                    }
                }
                else
                {
                    iw.WriteLine($"""
                        var bodyJson = System.Text.Json.JsonSerializer.Serialize(contract, _jsonOptions);
                        using var content = new System.Net.Http.StringContent(bodyJson, System.Text.Encoding.UTF8, "application/json");
                        """);
                }

                iw.WriteLine("request.Content = content;");
                iw.WriteLine();
            }

            var contractResultGenericPart = string.Empty;
            if (metadata.IsReturning)
                contractResultGenericPart = $"<{metadata.ReturnFullyQualifiedName}>";

            if (metadata.IsStreamReturnType)
            {
                iw.WriteLine($$"""
                    var response = await _http.SendAsync(request, ct);
                    var contentType = response.Content.Headers.ContentType?.MediaType?.ToLowerInvariant();
                    if (contentType == "application/json")
                    {
                        var contentStr = await response.Content.ReadAsStringAsync();
                        var result = System.Text.Json.JsonSerializer.Deserialize<Kanawanagasaki.BlazorContracts.DisposableContractResult<{{typeof(Stream).FullName}}>>(contentStr, _jsonOptions);
                        result.HttpResponse = response;
                        return result;
                    }
                    else
                    {
                        var stream = await response.Content.ReadAsStreamAsync();
                        return new Kanawanagasaki.BlazorContracts.DisposableContractResult<{{typeof(Stream).FullName}}>(stream)
                        {
                            HttpResponse = response
                        };
                    }
                    """);
            }
            else if (metadata.IsByteArrayReturnType)
            {
                iw.WriteLine($$"""
                    using var response = await _http.SendAsync(request, ct);
                    var contentType = response.Content.Headers.ContentType?.MediaType?.ToLowerInvariant();
                    if (contentType == "application/json")
                    {
                        var contentStr = await response.Content.ReadAsStringAsync();
                        return System.Text.Json.JsonSerializer.Deserialize<Kanawanagasaki.BlazorContracts.ContractResult<{{metadata.ReturnFullyQualifiedName}}>>(contentStr, _jsonOptions);
                    }
                    else if (contentType is not null && contentType.StartsWith("multipart/"))
                    {
                        var boundaryParam = response.Content.Headers.ContentType?.Parameters?.FirstOrDefault(p => p.Name?.Equals("boundary", System.StringComparison.OrdinalIgnoreCase) == true);
                        if (boundaryParam is null)
                            return new Kanawanagasaki.BlazorContracts.ContractResult<{{metadata.ReturnFullyQualifiedName}}>((int)response.StatusCode);

                        var boundary = boundaryParam.Value.Trim().Trim('"');
                        if (!boundary.StartsWith("--"))
                            boundary = "--" + boundary;
                        var boundaryBytes = System.Text.Encoding.UTF8.GetBytes(boundary);
                        var crlfcrlf = System.Text.Encoding.UTF8.GetBytes("\r\n\r\n");

                        var bytes = await response.Content.ReadAsByteArrayAsync();

                        int boundaryIndexStart = 0;
                        var boundaryIndices = new System.Collections.Generic.List<int>();
                        while (true)
                        {
                            var boundaryIndex = ByteIndexOf(bytes, boundaryBytes, boundaryIndexStart);
                            if (boundaryIndex < 0)
                                break;
                            boundaryIndices.Add(boundaryIndex);
                            boundaryIndexStart = boundaryIndex + boundaryBytes.Length;
                        }

                        Kanawanagasaki.BlazorContracts.ContractResult<{{metadata.ReturnFullyQualifiedName}}> contractResult = null;
                        byte[] byteArray = null;

                        for (int i = 0; i < boundaryIndices.Count - 1; i++)
                        {
                            var startPartIndex = boundaryIndices[i] + boundaryBytes.Length;
                            var endPartIndex = boundaryIndices[i + 1];

                            if (bytes[endPartIndex - 1] == '\n')
                                endPartIndex--;
                            if (bytes[endPartIndex - 1] == '\r')
                                endPartIndex--;

                            if (endPartIndex <= startPartIndex)
                                continue;

                            var headerEndIndex = ByteIndexOf(bytes, crlfcrlf, startPartIndex);
                            if (headerEndIndex < startPartIndex || endPartIndex <= headerEndIndex)
                                continue;

                            var header = System.Text.Encoding.UTF8.GetString(bytes, startPartIndex, headerEndIndex - startPartIndex);
                            var headerDict = new System.Collections.Generic.Dictionary<string, string>(System.StringComparer.OrdinalIgnoreCase);
                            var headerLines = header.Replace("\r", "").Split('\n', System.StringSplitOptions.RemoveEmptyEntries);
                            foreach (var line in headerLines)
                            {
                                var colonIndex = line.IndexOf(':');
                                if (colonIndex <= 0)
                                    continue;
                                var name = line.Substring(0, colonIndex).Trim().ToLowerInvariant();
                                var value = line.Substring(colonIndex + 1).Trim();
                                headerDict[name] = value;
                            }

                            var contentStartIndex = headerEndIndex += crlfcrlf.Length;
                            string partContentType = null;
                            if (headerDict.TryGetValue("content-type", out var partFullContentType))
                                partContentType = partFullContentType.Split(';')[0].Trim().ToLowerInvariant();

                            if (partContentType == "application/json")
                            {
                                var responseJson = System.Text.Encoding.UTF8.GetString(bytes, contentStartIndex, endPartIndex - contentStartIndex);
                                contractResult = System.Text.Json.JsonSerializer.Deserialize<Kanawanagasaki.BlazorContracts.ContractResult<byte[]>>(responseJson, _jsonOptions);
                            }
                            else
                            {
                                byteArray = new byte[endPartIndex - contentStartIndex];
                                System.Buffer.BlockCopy(bytes, contentStartIndex, byteArray, 0, byteArray.Length);
                            }

                            if (contractResult is not null && byteArray is not null)
                                break;
                        }

                        if (contractResult is null && byteArray is null)
                            return new Kanawanagasaki.BlazorContracts.ContractResult<{{metadata.ReturnFullyQualifiedName}}>((int)response.StatusCode);
                        else if (byteArray is null)
                            return contractResult;
                        else if (contractResult is null)
                            return new Kanawanagasaki.BlazorContracts.ContractResult<{{metadata.ReturnFullyQualifiedName}}>((int)response.StatusCode) { Data = byteArray };
                        else
                        {
                            contractResult.Data = byteArray;
                            return contractResult;
                        }
                    }
                    else
                    {
                        var bytes = await response.Content.ReadAsByteArrayAsync();
                        return new Kanawanagasaki.BlazorContracts.ContractResult<{{metadata.ReturnFullyQualifiedName}}>
                        {
                            StatusCode = (int)response.StatusCode,
                            Data = bytes
                        };
                    }
                    """);
            }
            else
            {
                iw.WriteLine($$"""
                    using var response = await _http.SendAsync(request, ct);
                    var contentType = response.Content.Headers.ContentType?.MediaType?.ToLowerInvariant();
                    
                    if (response.StatusCode is System.Net.HttpStatusCode.NoContent)
                    {
                        return new Kanawanagasaki.BlazorContracts.ContractResult{{contractResultGenericPart}}((int)response.StatusCode);
                    }
                    else if (contentType == "application/json")
                    {
                        var contentStr = await response.Content.ReadAsStringAsync();
                        return System.Text.Json.JsonSerializer.Deserialize<Kanawanagasaki.BlazorContracts.ContractResult{{contractResultGenericPart}}>(contentStr, _jsonOptions);
                    }
                    else
                    {
                        return new Kanawanagasaki.BlazorContracts.ContractResult{{contractResultGenericPart}}((int)response.StatusCode, "Unexpected content type " + contentType);
                    }
                    """);
            }

            iw.DecreaseAndWriteLine("}");
            iw.WriteLine("catch (System.OperationCanceledException)");
            iw.WriteLineAndIncrease("{");
            if (metadata.IsDisposableReturnType)
                iw.WriteLine($"return new Kanawanagasaki.BlazorContracts.DisposableContractResult{contractResultGenericPart}(499, \"Client Closed Request\");");
            else
                iw.WriteLine($"return new Kanawanagasaki.BlazorContracts.ContractResult{contractResultGenericPart}(499, \"Client Closed Request\");");
            iw.DecreaseAndWriteLine("}");
            iw.WriteLine("catch (System.Exception)");
            iw.WriteLineAndIncrease("{");
            if (metadata.IsDisposableReturnType)
                iw.WriteLine($"return new Kanawanagasaki.BlazorContracts.DisposableContractResult{contractResultGenericPart}(0, \"Network Error\");");
            else
                iw.WriteLine($"return new Kanawanagasaki.BlazorContracts.ContractResult{contractResultGenericPart}(0, \"Network Error\");");
            iw.DecreaseAndWriteLine("}");

            iw.DecreaseAndWriteLine("}");
        }

        iw.IndentLevel = 0;
        iw.WriteLine("""
                
                private static int ByteIndexOf(byte[] haystack, byte[] needle, int start)
                {
                    if (needle.Length == 0)
                        return start;
                    for (int i = start; i <= haystack.Length - needle.Length; i++)
                    {
                        var found = true;
                        for (int j = 0; j < needle.Length; j++)
                        {
                            if (haystack[i + j] != needle[j])
                            {
                                found = false;
                                break;
                            }
                        }
                        if (found)
                            return i;
                    }
                    return -1;
                }
            }
            """);

        context.AddSource("ClientContractsService.g.cs", sw.ToString());
    }
}
