namespace Kanawanagasaki.BlazorContracts.SourceGenerator;

using Microsoft.CodeAnalysis;
using System.Text;

[Generator]
public class ClientContractsExtensionsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var config = context.AnalyzerConfigOptionsProvider.Select((options, _) =>
        {
            options.GlobalOptions.TryGetValue("build_property.BlazorContracts", out var value);
            return value;
        });

        context.RegisterSourceOutput(config.Combine(context.CompilationProvider), Execute);
    }

    private void Execute(SourceProductionContext context, (string?, Compilation) tuple)
    {
        var (config, compilation) = tuple;
        var optIns = config?.ToLowerInvariant().Split(',') ?? [];
        if (!optIns.Contains("clientservice"))
            return;

        var sb = new StringBuilder();
        sb.AppendLine("""
            // <auto-generated/>
            namespace Kanawanagasaki.BlazorContracts.Client;
            using Microsoft.Extensions.DependencyInjection;
            public static class ClientContractsExtensions
            {
                public static Microsoft.Extensions.DependencyInjection.IServiceCollection AddContracts(this Microsoft.Extensions.DependencyInjection.IServiceCollection services)
                {
                    services.AddScoped<Kanawanagasaki.BlazorContracts.IContractsService, ClientContractsService>();
                    return services;
                }
                public static Microsoft.Extensions.DependencyInjection.IServiceCollection AddContracts<T>(this Microsoft.Extensions.DependencyInjection.IServiceCollection services) where T : ClientContractsService
                {
                    services.AddScoped<Kanawanagasaki.BlazorContracts.IContractsService, T>();
                    return services;
                }
            }
            """);
        context.AddSource("ClientContractsExtensions.g.cs", sb.ToString());
    }
}
