namespace Kanawanagasaki.BlazorContracts.SourceGenerator;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;

[Generator]
public class ContractsEndpointsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var config = context.AnalyzerConfigOptionsProvider.Select((options, _) =>
        {
            options.GlobalOptions.TryGetValue("build_property.BlazorContracts", out var value);
            return value;
        });

        var handlersDeclarations = context.SyntaxProvider.CreateSyntaxProvider
            (
                static (node, _) => node is ClassDeclarationSyntax classDecl && classDecl.BaseList is not null,
                static (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)ctx.Node)
            );

        var compilations = context.CompilationProvider
                                  .Combine(handlersDeclarations.Collect())
                                  .Select((tuple, _) =>
        {
            var (compilation, handlersSymbolds) = tuple;
            var ret = new List<HandlerMetadata>();

            foreach (var handler in handlersSymbolds)
            {
                if (handler is null)
                    continue;
                if (HandlerMetadata.TryCreate(handler, out var metadata) && metadata is not null)
                    ret.Add(metadata);
            }

            return ret.ToImmutableArray();
        });

        context.RegisterSourceOutput(config.Combine(compilations), Execute);
    }

    private void Execute(SourceProductionContext context, (string?, ImmutableArray<HandlerMetadata>) tuple)
    {
        var (config, list) = tuple;
        var optIns = config?.ToLowerInvariant().Split(',') ?? [];
        if (!optIns.Contains("endpoints"))
            return;

        using var sw = new StringWriter();
        using var iw = new IndentedTextWriter(sw);
        iw.WriteLine("""
            // <auto-generated/>
            #nullable enable
            namespace Kanawanagasaki.BlazorContracts;

            using Microsoft.Extensions.DependencyInjection;
            using Microsoft.AspNetCore.Builder;
            using System.Linq;

            public static class ContractsEndpoints
            {
                public static void MapContracts(this Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints)
                {
                    var jsonOptions = new System.Text.Json.JsonSerializerOptions
                    {
                        PropertyNamingPolicy = null,
                        DictionaryKeyPolicy = null,
                        DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull,
                        TypeInfoResolver = new System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver
                        {
                            Modifiers =
                            {
                                typeInfo =>
                                {
            """);

        foreach (var item in list)
        {
            if (item.Contract.VerbStr != "Post" && item.Contract.VerbStr != "Put")
                continue;
            if (item.Contract.IsMessagePack)
                continue;
            if (!item.Contract.HasBinaryProperty)
                continue;

            iw.IndentLevel = 6;
            iw.WriteLine($"if(typeInfo.Type == typeof({item.Contract.FullyQualifiedName}))");
            iw.WriteLine("{");

            iw.IndentLevel++;
            foreach (var prop in item.Contract.Properties.Values)
            {
                if (prop.IsByteArray || prop.IsContractFile)
                    iw.WriteLine($$"""
                        var contractProperty{{prop.Name}} = typeInfo.Properties.FirstOrDefault(property =>
                            property.Name == nameof({{item.Contract.FullyQualifiedName}}.{{prop.Name}})
                            || (property.AttributeProvider is System.Reflection.PropertyInfo contractClrProperty{{prop.Name}} && contractClrProperty{{prop.Name}}.Name == nameof({{item.Contract.FullyQualifiedName}}.{{prop.Name}})));
                        if (contractProperty{{prop.Name}} is not null)
                            typeInfo.Properties.Remove(contractProperty{{prop.Name}});
                        """);
            }

            iw.DecreaseAndWriteLine("}");
        }

        iw.IndentLevel = 0;
        iw.WriteLine($$"""
                                    if(typeInfo.Type == typeof(Kanawanagasaki.BlazorContracts.ContractResult<byte[]>))
                                    {
                                        var dataProperty = typeInfo.Properties.FirstOrDefault(property =>
                                            property.Name == nameof(Kanawanagasaki.BlazorContracts.ContractResult<byte[]>.Data)
                                            || (property.AttributeProvider is System.Reflection.PropertyInfo dataClrProperty && dataClrProperty.Name == nameof(Kanawanagasaki.BlazorContracts.ContractResult<byte[]>.Data)));
                                        if (dataProperty is not null)
                                            typeInfo.Properties.Remove(dataProperty);
                                    }
                                    if(typeInfo.Type == typeof(Kanawanagasaki.BlazorContracts.ContractResult<{{typeof(Stream).FullName}}>))
                                    {
                                        var streamDataProperty = typeInfo.Properties.FirstOrDefault(property =>
                                            property.Name == nameof(Kanawanagasaki.BlazorContracts.ContractResult<{{typeof(Stream).FullName}}>.Data)
                                            || (property.AttributeProvider is System.Reflection.PropertyInfo streamDataClrProperty && streamDataClrProperty.Name == nameof(Kanawanagasaki.BlazorContracts.ContractResult<{{typeof(Stream).FullName}}>.Data)));
                                        if (streamDataProperty is not null)
                                            typeInfo.Properties.Remove(streamDataProperty);
                                    }
                                }
                            }
                        }
                    };
            """);

        var unsafeAccessors = new List<string>();

        foreach (var item in list)
        {
            var preferMessagePack = item.Contract.IsMessagePack ? "true" : "false";
            var messagePack = item.Contract.IsReturnMessagePack ? "true" : "false";
            var compressed = item.Contract.IsCompressed ? "true" : "false";

            iw.IndentLevel = 2;
            iw.WriteLine();
            iw.WriteLineAndIncrease($"endpoints.Map{item.Contract.VerbStr}(\"{item.Contract.Endpoint}\", async (");

            var isPostOrPut = item.Contract.VerbStr == "Post" || item.Contract.VerbStr == "Put";

            iw.WriteLine("Microsoft.AspNetCore.Http.HttpRequest httpRequest,");
            iw.WriteLine("Microsoft.AspNetCore.Http.HttpResponse httpResponse,");

            var routeParts = item.Contract.Endpoint.Split(['/', '\\'], StringSplitOptions.RemoveEmptyEntries)
                .Where(x => 2 < x.Length && x[0] == '{' && x[x.Length - 1] == '}')
                .Select(x => x.Substring(1, x.Length - 2))
                .ToArray();
            foreach (var routePart in routeParts)
                if (item.Contract.Properties.TryGetValue(routePart, out var prop))
                    iw.WriteLine($"[Microsoft.AspNetCore.Mvc.FromRoute] {prop.FullyQualifiedName} {routePart},");

            if (item.Contract.VerbStr == "Get" || item.Contract.VerbStr == "Delete")
            {
                foreach (var kv in item.Contract.Properties)
                {
                    if (0 <= routeParts.IndexOf(kv.Key))
                        continue;

                    if (kv.Value.IsReferenceType || kv.Value.IsNullable)
                    {
                        if (kv.Value.JsonPropertyName is null)
                            iw.WriteLine($"[Microsoft.AspNetCore.Mvc.FromQuery] {kv.Value.FullyQualifiedName} {kv.Key},");
                        else
                        {
                            var queryKey = kv.Value.JsonPropertyName.Replace("\\", "\\\\").Replace("\"", "\\\"");
                            iw.WriteLine($"[Microsoft.AspNetCore.Mvc.FromQuery(Name = \"{queryKey}\")] {kv.Value.FullyQualifiedName} {kv.Key},");
                        }
                    }
                }
            }

            foreach (var (injectedServiceType, injectedServiceIndex) in item.HandlerInjectedServicesTypes)
                iw.WriteLine($"[Microsoft.AspNetCore.Mvc.FromServices] {injectedServiceType} injectedService{injectedServiceIndex},");

            iw.WriteLine($"Microsoft.Extensions.Logging.ILogger<{item.HandlerFullyQualifiedName}> logger,");

            if (item.Contract.VerbStr == "Get" || item.Contract.VerbStr == "Delete")
            {
                foreach (var kv in item.Contract.Properties)
                {
                    if (0 <= routeParts.IndexOf(kv.Key))
                        continue;

                    if (!kv.Value.IsReferenceType && !kv.Value.IsNullable)
                    {
                        if (kv.Value.JsonPropertyName is null)
                            iw.WriteLine($"[Microsoft.AspNetCore.Mvc.FromQuery] {kv.Value.FullyQualifiedName} {kv.Key} = default,");
                        else
                        {
                            var queryKey = kv.Value.JsonPropertyName.Replace("\\", "\\\\").Replace("\"", "\\\"");
                            iw.WriteLine($"[Microsoft.AspNetCore.Mvc.FromQuery(Name = \"{queryKey}\")] {kv.Value.FullyQualifiedName} {kv.Key} = default,");
                        }
                    }
                }
            }

            iw.WriteLine("System.Threading.CancellationToken ct = default) =>");
            iw.DecreaseAndWriteLine("{");

            if (item.Contract.IsDisposableReturnType)
            {
                iw.IncreaseAndWriteLine("var toDispose = new System.Collections.Generic.List<System.IDisposable>();");
                if (isPostOrPut)
                    iw.WriteLine("System.Collections.Generic.Dictionary<string, Kanawanagasaki.BlazorContracts.ContractMultipart.Part>? multipartParts = null;");
            }
            else
            {
                iw.IndentLevel++;
                if (isPostOrPut)
                    iw.WriteLine("System.Collections.Generic.Dictionary<string, Kanawanagasaki.BlazorContracts.ContractMultipart.Part>? multipartParts = null;");
            }

            iw.WriteLine("try");
            iw.WriteLineAndIncrease("{");

            if (isPostOrPut)
            {
                iw.WriteLineAndIncrease($$"""
                    {{item.Contract.FullyQualifiedName}}? contract;
                    if (Kanawanagasaki.BlazorContracts.ContractMediaTypes.IsMultipart(httpRequest.ContentType))
                    {
                        var parts = await Kanawanagasaki.BlazorContracts.ContractMultipart.ParseAsync(httpRequest.Body, httpRequest.ContentType, ct);
                        multipartParts = parts;
                        if (parts is null || !parts.TryGetValue("{{item.Contract.Name}}", out var contractPart))
                        {
                            await Kanawanagasaki.BlazorContracts.ContractsWire.WriteBadRequestAsync(httpResponse, jsonOptions, messagePack: {{messagePack}}, compressed: {{compressed}}, compressionLevel: {{item.Contract.CompressionLevelSource}}, ct: ct);
                            return;
                        }
                        contract = await Kanawanagasaki.BlazorContracts.ContractBody.ParseAsync<{{item.Contract.FullyQualifiedName}}>(contractPart.Stream, contractPart.ContentType, jsonOptions, preferMessagePack: {{preferMessagePack}}, ct: ct);
                        if (contract is null)
                        {
                            await Kanawanagasaki.BlazorContracts.ContractsWire.WriteBadRequestAsync(httpResponse, jsonOptions, messagePack: {{messagePack}}, compressed: {{compressed}}, compressionLevel: {{item.Contract.CompressionLevelSource}}, ct: ct);
                            return;
                        }
                    """);

                foreach (var prop in item.Contract.Properties.Values)
                {
                    if (item.Contract.IsMessagePack && prop.IsByteArray)
                        continue;

                    if (prop.IsByteArray)
                    {
                        iw.WriteLineAndIncrease($$"""
                            if (parts.TryGetValue("{{prop.Name}}", out var bytesPart{{prop.Name}}))
                            {
                                using var bytesBuffer{{prop.Name}} = new System.IO.MemoryStream();
                                await bytesPart{{prop.Name}}.Stream.CopyToAsync(bytesBuffer{{prop.Name}}, ct);
                            """);

                        var bytesAssignment = GetBackingFieldAssignmentStatement(item, prop.Name, prop, $"bytesBuffer{prop.Name}.ToArray()", unsafeAccessors);
                        if (bytesAssignment is not null)
                            iw.WriteLine(bytesAssignment);

                        iw.DecreaseAndWriteLine("}");
                    }
                    else if (prop.IsContractFile)
                    {
                        iw.WriteLineAndIncrease($$"""
                            if (parts.TryGetValue("{{prop.Name}}", out var filePart{{prop.Name}}))
                            {
                            """);
                        var fileAssignment = GetBackingFieldAssignmentStatement(item, prop.Name, prop, $"new Kanawanagasaki.BlazorContracts.ContractFile(filePart{prop.Name}.Stream, filePart{prop.Name}.FileName ?? \"file\", filePart{prop.Name}.ContentType ?? \"application/octet-stream\", filePart{prop.Name}.Length)", unsafeAccessors);
                        if (fileAssignment is not null)
                            iw.WriteLine(fileAssignment);
                        iw.DecreaseAndWriteLine("}");
                    }
                }

                iw.DecreaseAndWriteLine($$"""
                    }
                    else
                    {
                        contract = await Kanawanagasaki.BlazorContracts.ContractsWire.ParseBodyAsync<{{item.Contract.FullyQualifiedName}}>(httpRequest, jsonOptions, preferMessagePack: {{preferMessagePack}}, ct: ct);
                        if (contract is null)
                        {
                            await Kanawanagasaki.BlazorContracts.ContractsWire.WriteBadRequestAsync(httpResponse, jsonOptions, messagePack: {{messagePack}}, compressed: {{compressed}}, compressionLevel: {{item.Contract.CompressionLevelSource}}, ct: ct);
                            return;
                        }
                    }
                    """);
            }

            if (item.Contract.VerbStr == "Get" || item.Contract.VerbStr == "Delete")
            {
                iw.WriteLine($"var contract = new {item.Contract.FullyQualifiedName}");
                iw.WriteLineAndIncrease("{");
                foreach (var propName in item.Contract.Properties.Keys)
                {
                    if (item.Contract.Properties[propName].HasPublicSetter)
                        iw.WriteLine($"{propName} = {propName},");
                }
                iw.DecreaseAndWriteLine("};");

                foreach (var propName in item.Contract.Properties.Keys)
                {
                    var contractProp = item.Contract.Properties[propName];
                    if (contractProp.HasPublicSetter)
                        continue;

                    var getterOnlyAssignment = GetBackingFieldAssignmentStatement(item, propName, contractProp, propName, unsafeAccessors);
                    if (getterOnlyAssignment is not null)
                        iw.WriteLine(getterOnlyAssignment);
                }
            }

            if (0 < routeParts.Length)
            {
                foreach (var routePart in routeParts)
                {
                    if (!item.Contract.Properties.TryGetValue(routePart, out var routeProp))
                        continue;

                    var routeAssignment = GetBackingFieldAssignmentStatement(item, routePart, routeProp, routePart, unsafeAccessors);
                    if (routeAssignment is not null)
                        iw.WriteLine(routeAssignment);
                }
            }

            var handlerConstructorArgs = string.Join(", ", item.HandlerConstructorInjectedServicesTypes.Select(x => $"injectedService{x.Index}"));
            iw.Write($"var handler = new {item.HandlerFullyQualifiedName}({handlerConstructorArgs})");
            if (0 < item.HandlerPropertiesInjectedServicesTypes.Count)
            {
                iw.WriteLine();
                iw.WriteLineAndIncrease("{");
                iw.WriteLineAndDecrease(string.Join(",\n", item.HandlerPropertiesInjectedServicesTypes.Select(x => $"{x.Name} = injectedService{x.Index}")));
                iw.Write("}");
            }
            iw.WriteLine(";");

            iw.WriteLine("var result = await handler.HandleAsync(contract, ct);");

            if (item.Contract.IsDisposableReturnType)
            {
                iw.WriteLineAndIncrease("if(result.Data is not null)");
                iw.WriteLineAndDecrease("toDispose.Add(result.Data);");
            }

            if (item.Contract.IsStreamReturnType)
                iw.WriteLine($"await Kanawanagasaki.BlazorContracts.ContractsWire.WriteStreamResultAsync(httpResponse, result, jsonOptions, messagePack: {messagePack}, compressed: {compressed}, compressionLevel: {item.Contract.CompressionLevelSource}, ct: ct);");
            else if (item.Contract.IsByteArrayReturnType)
                iw.WriteLine($"await Kanawanagasaki.BlazorContracts.ContractsWire.WriteBytesResultAsync(httpResponse, result, jsonOptions, messagePack: {messagePack}, compressed: {compressed}, compressionLevel: {item.Contract.CompressionLevelSource}, contractName: \"{item.Contract.Name}\", ct: ct);");
            else
                iw.WriteLine($"await Kanawanagasaki.BlazorContracts.ContractsWire.WriteResultAsync(httpResponse, result, jsonOptions, messagePack: {messagePack}, compressed: {compressed}, compressionLevel: {item.Contract.CompressionLevelSource}, ct: ct);");

            iw.DecreaseAndWriteLine("}");
            iw.WriteLine("catch (System.Exception e)");
            iw.WriteLineAndIncrease("{");
            iw.WriteLine("logger.LogError(e, \"Failed to handle a contract\");");
            iw.WriteLine($"await Kanawanagasaki.BlazorContracts.ContractsWire.WriteErrorAsync(httpResponse, jsonOptions, messagePack: {messagePack}, compressed: {compressed}, compressionLevel: {item.Contract.CompressionLevelSource}, ct: ct);");
            iw.DecreaseAndWriteLine("}");

            if (item.Contract.IsDisposableReturnType || isPostOrPut)
            {
                iw.WriteLine("finally");
                iw.WriteLineAndIncrease("{");
                if (isPostOrPut)
                {
                    iw.WriteLine("if (multipartParts is not null)");
                    iw.WriteLineAndIncrease("{");
                    iw.WriteLine("foreach (var part in multipartParts.Values)");
                    iw.WriteLine("    await part.DisposeAsync();");
                    iw.DecreaseAndWriteLine("}");
                }
                if (item.Contract.IsDisposableReturnType)
                {
                    iw.WriteLine("foreach (var disposable in toDispose)");
                    iw.WriteLineAndIncrease("{");
                    iw.WriteLine("if(disposable is IAsyncDisposable asyncDisposable)");
                    iw.WriteLine("    await asyncDisposable.DisposeAsync();");
                    iw.WriteLine("else");
                    iw.WriteLine("    disposable.Dispose();");
                    iw.DecreaseAndWriteLine("}");
                }
                iw.DecreaseAndWriteLine("}");
            }

            iw.DecreaseAndWriteLine("})");
            iw.Write(".WithMetadata(new Kanawanagasaki.BlazorContracts.ContractAuthEndpointMarker())");
            foreach (var attr in item.EndpointAttributes)
            {
                iw.WriteLine();
                iw.Write($".WithMetadata({attr.AttributeInstanceSource})");
            }
            iw.WriteLine(";");
        }

        iw.DecreaseAndWriteLine("}");

        if (0 < unsafeAccessors.Count)
        {
            iw.WriteLine();
            foreach (var accessor in unsafeAccessors)
                iw.WriteLine(accessor);
        }

        iw.DecreaseAndWriteLine("}");

        iw.WriteLine();
        iw.WriteLine(ContractsWireTemplate.Source);

        context.AddSource("ContractsEndpoints.g.cs", sw.ToString());
    }

    private static string? GetBackingFieldAssignmentStatement(HandlerMetadata item, string propName, PropertyMetadata prop, string valueExpression, List<string> unsafeAccessors)
    {
        if ((prop.HasPublicSetter && !prop.IsInitOnly) || item.Contract.FullyQualifiedName.Contains('<'))
            return $"contract.{propName} = {valueExpression};";

        if (!prop.HasBackingField)
            return null;

        var accessorName = $"backingField{unsafeAccessors.Count + 1}";
        unsafeAccessors.Add($$"""
                [System.Runtime.CompilerServices.UnsafeAccessor(System.Runtime.CompilerServices.UnsafeAccessorKind.Field, Name = "<{{propName}}>k__BackingField")]
                private static extern ref {{prop.FullyQualifiedName}} {{accessorName}}({{item.Contract.FullyQualifiedName}} target);
            """);
        return $"{accessorName}(contract) = {valueExpression};";
    }
}
