namespace Kanawanagasaki.BlazorContracts.SourceGenerator;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;

[Generator]
public class ContractsServiceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var config = context.AnalyzerConfigOptionsProvider.Select((options, _) =>
        {
            options.GlobalOptions.TryGetValue("build_property.BlazorContracts", out var value);
            return value;
        });

        var handlersDeclarations = context.SyntaxProvider.CreateSyntaxProvider
        (
            static (node, _) => node is ClassDeclarationSyntax classDecl && classDecl.BaseList is not null,
            static (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)ctx.Node)
        );

        var compilations = context.CompilationProvider
            .Combine(handlersDeclarations.Collect())
            .Select((tuple, _) =>
            {
                var (compilation, handlersSymbolds) = tuple;
                var ret = new List<HandlerMetadata>();

                foreach (var handler in handlersSymbolds)
                {
                    if (handler is null)
                        continue;
                    if (HandlerMetadata.TryCreate(handler, out var metadata) && metadata is not null)
                        ret.Add(metadata);
                }

                return ret.ToImmutableArray();
            });

        context.RegisterSourceOutput(config.Combine(compilations), Execute);
    }

    private void Execute(SourceProductionContext context, (string?, ImmutableArray<HandlerMetadata>) tuple)
    {
        var (config, list) = tuple;
        var optIns = config?.ToLowerInvariant().Split(',') ?? [];
        if (!optIns.Contains("serverservice"))
            return;

        var injectedServices = new Dictionary<string, string>();

        foreach (var meta in list)
        {
            foreach (var (injectedServiceType, _) in meta.HandlerInjectedServicesTypes)
            {
                if (!injectedServices.ContainsKey(injectedServiceType))
                    injectedServices[injectedServiceType] = $"_injected_service_" + (injectedServices.Count + 1);
            }
        }

        var hasAuthAttributes = list.Any(m => m.EndpointAttributes.Any(a => a.IsAuthAttribute));
        var hasPolicyAuth = list.Any(m => m.EndpointAttributes.Any(a => a.IsAuthorize && a.Policy is not null));

        using var sw = new StringWriter();
        using var iw = new IndentedTextWriter(sw);
        iw.WriteLine("// <auto-generated/>");
        iw.WriteLine("namespace Kanawanagasaki.BlazorContracts;");

        iw.WriteLine();

        iw.WriteLine("""
            public static class ContractsServiceExtension
            {
                public static Microsoft.Extensions.DependencyInjection.IServiceCollection AddContracts(this Microsoft.Extensions.DependencyInjection.IServiceCollection services)
                {
                    services.AddHttpContextAccessor();
                    services.AddScoped<Kanawanagasaki.BlazorContracts.IContractsService, ContractsService>();
                    return services;
                }
            }
            """);

        iw.WriteLine();

        iw.WriteLine("public class ContractsService : Kanawanagasaki.BlazorContracts.IContractsService");
        iw.WriteLineAndIncrease("{");

        iw.WriteLine("private readonly Microsoft.Extensions.Logging.ILogger<ContractsService> _logger;");
        foreach (var kv in injectedServices)
            iw.WriteLine($"private readonly {kv.Key} {kv.Value};");

        if (hasAuthAttributes)
        {
            iw.WriteLine("private readonly Microsoft.AspNetCore.Http.IHttpContextAccessor _httpContextAccessor;");
            if (hasPolicyAuth)
                iw.WriteLine("private readonly Microsoft.AspNetCore.Authorization.IAuthorizationService _authorizationService;");
        }

        iw.WriteLine();

        iw.WriteLineAndIncrease("public ContractsService(");
        var constructorParams = new List<string>();
        foreach (var kv in injectedServices)
            constructorParams.Add($"{kv.Key} {kv.Value}");
        if (hasAuthAttributes)
        {
            constructorParams.Add("Microsoft.AspNetCore.Http.IHttpContextAccessor httpContextAccessor");
            if (hasPolicyAuth)
                constructorParams.Add("Microsoft.AspNetCore.Authorization.IAuthorizationService authorizationService");
        }
        constructorParams.Add("Microsoft.Extensions.Logging.ILogger<ContractsService> logger");
        iw.WriteLine(string.Join(",\n", constructorParams));
        iw.DecreaseAndWriteLine(")");
        iw.WriteLineAndIncrease("{");
        iw.WriteLine("this._logger = logger;");
        foreach (var kv in injectedServices)
            iw.WriteLine($"this.{kv.Value} = {kv.Value};");
        if (hasAuthAttributes)
        {
            iw.WriteLine("this._httpContextAccessor = httpContextAccessor;");
            if (hasPolicyAuth)
                iw.WriteLine("this._authorizationService = authorizationService;");
        }
        iw.DecreaseAndWriteLine("}");

        foreach (var metadata in list)
        {
            var returnTypeGenericPart = string.Empty;
            if (metadata.Contract.IsReturning)
                returnTypeGenericPart = $"<{metadata.Contract.ReturnFullyQualifiedName}>";

            iw.WriteLine();

            if (metadata.Contract.IsDisposableReturnType)
                iw.WriteLine($"public async Task<{Constants.DisposableContractResultFullName}<{metadata.Contract.ReturnFullyQualifiedName}>> ProcessAsync({metadata.Contract.FullyQualifiedName} contract, System.Threading.CancellationToken ct = default)");
            else if (metadata.Contract.IsReturning)
                iw.WriteLine($"public async Task<{Constants.ContractResultFullName}<{metadata.Contract.ReturnFullyQualifiedName}>> ProcessAsync({metadata.Contract.FullyQualifiedName} contract, System.Threading.CancellationToken ct = default)");
            else
                iw.WriteLine($"public async Task<{Constants.ContractResultFullName}> ProcessAsync({metadata.Contract.FullyQualifiedName} contract, System.Threading.CancellationToken ct = default)");
            iw.WriteLineAndIncrease("{");

            GenerateAuthorizationChecks(iw, metadata, returnTypeGenericPart);

            iw.WriteLine("try");
            iw.WriteLineAndIncrease("{");

            var constructorNames = metadata.HandlerConstructorInjectedServicesTypes
                .Select(x => injectedServices.TryGetValue(x.TypeName, out var fieldName) ? fieldName : null)
                .Where(x => x is not null);

            iw.Write($"var handler = new {metadata.HandlerFullyQualifiedName}({string.Join(",", constructorNames)})");
            if (0 < metadata.HandlerPropertiesInjectedServicesTypes.Count)
            {
                iw.WriteLine();
                iw.WriteLineAndIncrease("{");
                var isFirst = true;
                foreach (var injectProp in metadata.HandlerPropertiesInjectedServicesTypes)
                {
                    if (!injectedServices.TryGetValue(injectProp.TypeName, out var fieldName))
                        continue;

                    if (isFirst)
                        isFirst = false;
                    else
                        iw.WriteLine(",");

                    iw.Write($"{injectProp.Name} = {fieldName}");
                }
                iw.WriteLineAndDecrease("");
                iw.Write("}");
            }
            iw.WriteLine(";");
            iw.WriteLine("var result = await handler.HandleAsync(contract, ct);");
            if (metadata.Contract.IsDisposableReturnType)
                iw.WriteLine($"return result.AsDisposable();");
            else
                iw.WriteLine($"return result;");

            iw.DecreaseAndWriteLine("}");
            iw.WriteLine("catch (System.OperationCanceledException)");
            iw.WriteLineAndIncrease("{");
            if (metadata.Contract.IsDisposableReturnType)
                iw.WriteLine($"return new Kanawanagasaki.BlazorContracts.DisposableContractResult{returnTypeGenericPart}(499, \"Client Closed Request\");");
            else
                iw.WriteLine($"return new Kanawanagasaki.BlazorContracts.ContractResult{returnTypeGenericPart}(499, \"Client Closed Request\");");
            iw.DecreaseAndWriteLine("}");
            iw.WriteLine("catch (System.Exception e)");
            iw.WriteLineAndIncrease("{");
            iw.WriteLine("_logger.LogError(e, \"Failed to process a contract\");");
            if (metadata.Contract.IsDisposableReturnType)
                iw.WriteLine($"return new Kanawanagasaki.BlazorContracts.DisposableContractResult{returnTypeGenericPart}(500, \"Internal Server Error\");");
            else
                iw.WriteLine($"return new Kanawanagasaki.BlazorContracts.ContractResult{returnTypeGenericPart}(500, \"Internal Server Error\");");
            iw.DecreaseAndWriteLine("}");

            iw.DecreaseAndWriteLine("}");
        }

        iw.DecreaseAndWriteLine("}");

        context.AddSource("ContractsService.g.cs", sw.ToString());
    }

    private void GenerateAuthorizationChecks(IndentedTextWriter iw, HandlerMetadata metadata, string returnTypeGenericPart)
    {
        var authAttributes = metadata.EndpointAttributes.Where(a => a.IsAuthAttribute).ToList();
        if (authAttributes.Count == 0)
            return;

        if (authAttributes.Any(a => a.IsAllowAnonymous))
            return;

        var authorizeAttributes = authAttributes.Where(a => a.IsAuthorize).ToList();
        if (authorizeAttributes.Count == 0)
            return;

        iw.WriteLine("var __user = _httpContextAccessor.HttpContext?.User;");
        iw.WriteLine("if (__user is null || __user.Identity is null || !__user.Identity.IsAuthenticated)");
        iw.WriteLineAndIncrease("{");
        if (metadata.Contract.IsDisposableReturnType)
            iw.WriteLine($"return new Kanawanagasaki.BlazorContracts.DisposableContractResult{returnTypeGenericPart}(401, \"Unauthorized\");");
        else
            iw.WriteLine($"return new Kanawanagasaki.BlazorContracts.ContractResult{returnTypeGenericPart}(401, \"Unauthorized\");");
        iw.DecreaseAndWriteLine("}");

        foreach (var authAttr in authorizeAttributes)
        {
            if (authAttr.Roles is not null)
            {
                var roles = authAttr.Roles.Split(',').Select(r => r.Trim()).Where(r => r.Length > 0).ToArray();
                if (0 < roles.Length)
                {
                    if (roles.Length == 1)
                    {
                        iw.WriteLine($"if (!__user.IsInRole(\"{roles[0].Replace("\"", "\\\"")}\"))");
                    }
                    else
                    {
                        iw.Write("if (!(");
                        var roleChecks = roles.Select(r => $"__user.IsInRole(\"{r.Replace("\"", "\\\"")}\")");
                        iw.Write(string.Join(" || ", roleChecks));
                        iw.WriteLine("))");
                    }
                    iw.WriteLineAndIncrease("{");
                    if (metadata.Contract.IsDisposableReturnType)
                        iw.WriteLine($"return new Kanawanagasaki.BlazorContracts.DisposableContractResult{returnTypeGenericPart}(403, \"Forbidden\");");
                    else
                        iw.WriteLine($"return new Kanawanagasaki.BlazorContracts.ContractResult{returnTypeGenericPart}(403, \"Forbidden\");");
                    iw.DecreaseAndWriteLine("}");
                }
            }

            if (authAttr.Policy is not null)
            {
                iw.WriteLine($"var __authResult = await Microsoft.AspNetCore.Authorization.AuthorizationServiceExtensions.AuthorizeAsync(_authorizationService, __user, \"{authAttr.Policy.Replace("\"", "\\\"")}\");");
                iw.WriteLine("if (!__authResult.Succeeded)");
                iw.WriteLineAndIncrease("{");
                if (metadata.Contract.IsDisposableReturnType)
                    iw.WriteLine($"return new Kanawanagasaki.BlazorContracts.DisposableContractResult{returnTypeGenericPart}(403, \"Forbidden\");");
                else
                    iw.WriteLine($"return new Kanawanagasaki.BlazorContracts.ContractResult{returnTypeGenericPart}(403, \"Forbidden\");");
                iw.DecreaseAndWriteLine("}");
            }

            if (authAttr.AuthenticationSchemes is not null)
            {
                var schemes = authAttr.AuthenticationSchemes.Split(',').Select(s => s.Trim()).Where(s => 0 < s.Length).ToArray();
                if (schemes.Length > 0)
                {
                    iw.WriteLine($"if (!__user.Identities.Any(__id => __id.AuthenticationType is not null && new[] {{ {string.Join(", ", schemes.Select(s => $"\"{s.Replace("\"", "\\\"")}\""))} }}.Contains(__id.AuthenticationType)))");
                    iw.WriteLineAndIncrease("{");
                    if (metadata.Contract.IsDisposableReturnType)
                        iw.WriteLine($"return new Kanawanagasaki.BlazorContracts.DisposableContractResult{returnTypeGenericPart}(401, \"Unauthorized\");");
                    else
                        iw.WriteLine($"return new Kanawanagasaki.BlazorContracts.ContractResult{returnTypeGenericPart}(401, \"Unauthorized\");");
                    iw.DecreaseAndWriteLine("}");
                }
            }
        }
    }
}
