namespace Kanawanagasaki.BlazorContracts.SourceGenerator;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;

[Generator]
public class ContractsServiceGenerator : IIncrementalGenerator
{
    private static readonly SymbolDisplayFormat SYMB_DISPLAY_FORMAT_GENERICS = new
    (
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
        genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters
    );

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlersDeclarations = context.SyntaxProvider.CreateSyntaxProvider
        (
            static (node, _) => node is ClassDeclarationSyntax classDecl && classDecl.BaseList is not null,
            static (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)ctx.Node)
        );

        var compilations = context.CompilationProvider.Combine(handlersDeclarations.Collect());

        context.RegisterSourceOutput(compilations, Execute);
    }


    private void Execute(SourceProductionContext context, (Compilation, ImmutableArray<INamedTypeSymbol?>) tuple)
    {
        var (compilation, handlersSymbols) = tuple;

        var injectedServices = new Dictionary<string, string>();
        var noResponseContracts = new List<(string contractType, string handlerType, HashSet<string> servicesNames)>();
        var withResponseContracts = new List<(string contractType, string handlerType, HashSet<string> servicesNames, string responseType)>();

        foreach (var handler in handlersSymbols)
        {
            if (handler is null)
                continue;

            var handlerInterface = handler.AllInterfaces.FirstOrDefault(
                x => x.ContainingNamespace.ToString() + "." + x.Name == "Kanawanagasaki.BlazorContracts.IContractHandler");
            if (handlerInterface is null)
                continue;
            if (handlerInterface.TypeArguments.Length == 0)
                continue;

            var contractType = handlerInterface.TypeArguments[0];
            if (contractType is not INamedTypeSymbol contract)
                continue;

            var servicesTypes = new HashSet<string>();
            var constructor = handler.Constructors.FirstOrDefault(x => x.DeclaredAccessibility is Accessibility.Public);
            if (constructor is not null)
            {
                foreach (var param in constructor.Parameters)
                {
                    var fullname = param.Type.ToDisplayString(SYMB_DISPLAY_FORMAT_GENERICS);

                    if (!injectedServices.ContainsKey(fullname))
                        injectedServices[fullname] = $"_injected_service_" + (injectedServices.Count + 1);

                    servicesTypes.Add(injectedServices[fullname]);
                }
            }

            if (handlerInterface.TypeArguments.Length < 2)
            {
                noResponseContracts.Add(
                (
                    $"{contract.ContainingNamespace}.{contract.Name}",
                    $"{handler.ContainingNamespace}.{handler.Name}",
                    servicesTypes
                ));
            }
            else
            {
                var responseType = handlerInterface.TypeArguments[1];
                if (responseType is INamedTypeSymbol response)
                {
                    withResponseContracts.Add(
                    (
                        $"{contract.ContainingNamespace}.{contract.Name}",
                        $"{handler.ContainingNamespace}.{handler.Name}",
                        servicesTypes,
                        $"{response.ContainingNamespace}.{response.Name}"
                    ));
                }
                else if (responseType is IArrayTypeSymbol arr && arr.ElementType is INamedTypeSymbol response2)
                {
                    withResponseContracts.Add(
                    (
                        $"{contract.ContainingNamespace}.{contract.Name}",
                        $"{handler.ContainingNamespace}.{handler.Name}",
                        servicesTypes,
                        $"{response2.ContainingNamespace}.{response2.Name}[]"
                    ));
                }
            }
        }

        using var sw = new StringWriter();
        using var iw = new IndentedTextWriter(sw);
        iw.WriteLine("// <auto-generated/>");
        iw.WriteLine("namespace Kanawanagasaki.BlazorContracts;");
        iw.WriteLine();
        iw.WriteLine("public class ContractsService : Kanawanagasaki.BlazorContracts.IContractsService");
        iw.WriteLineAndIncrease("{");

        iw.WriteLine("private readonly Microsoft.Extensions.Logging.ILogger<ContractsService> _logger;");
        foreach (var kv in injectedServices)
            iw.WriteLine($"private readonly {kv.Key} {kv.Value};");

        iw.WriteLine();

        iw.WriteLineAndIncrease("public ContractsService(");
        iw.WriteLine(string.Join(",\n", injectedServices.Select(kv => $"{kv.Key} {kv.Value}").Concat(["Microsoft.Extensions.Logging.ILogger<ContractsService> logger"])));
        iw.DecreaseAndWriteLine(")");
        iw.WriteLineAndIncrease("{");
        iw.WriteLine("this._logger = logger;");
        foreach (var kv in injectedServices)
            iw.WriteLine($"this.{kv.Value} = {kv.Value};");
        iw.DecreaseAndWriteLine("}");

        iw.WriteLine();

        iw.WriteLine("public System.Threading.Tasks.Task<Kanawanagasaki.BlazorContracts.ContractResult> ProcessAsync(Kanawanagasaki.BlazorContracts.IContract req)");
        iw.WriteLineAndIncrease("{");
        iw.WriteLine("try");
        iw.WriteLineAndIncrease("{");
        iw.WriteLine("switch (req)");
        iw.WriteLineAndIncrease("{");
        for (int i = 0; i < noResponseContracts.Count; i++)
        {
            var meta = noResponseContracts[i];
            iw.WriteLineAndIncrease($"case {meta.contractType} _contract_{i + 1}:");
            iw.WriteLine($"var _handler_{i + 1} = new {meta.handlerType}({string.Join(",", meta.servicesNames)});");
            iw.WriteLine($"return _handler_{i + 1}.HandleAsync(_contract_{i + 1}, default);");
            iw.IndentLevel--;
        }
        iw.WriteLine("default: return System.Threading.Tasks.Task.FromResult(new Kanawanagasaki.BlazorContracts.ContractResult(405));");
        iw.DecreaseAndWriteLine("}");
        iw.DecreaseAndWriteLine("}");
        iw.WriteLine("catch (System.Exception e)");
        iw.WriteLineAndIncrease("{");
        iw.WriteLine("_logger.LogError(e, \"Failed to process a contract\");");
        iw.WriteLine("return System.Threading.Tasks.Task.FromResult(new Kanawanagasaki.BlazorContracts.ContractResult(500, \"Internal Server Error\"));");
        iw.DecreaseAndWriteLine("}");
        iw.DecreaseAndWriteLine("}");

        iw.WriteLine();

        iw.WriteLine("public async System.Threading.Tasks.Task<Kanawanagasaki.BlazorContracts.ContractResult<TResponse>> ProcessAsync<TResponse>(Kanawanagasaki.BlazorContracts.IContract<TResponse> req) where TResponse : class");
        iw.WriteLineAndIncrease("{");
        iw.WriteLine("try");
        iw.WriteLineAndIncrease("{");
        iw.WriteLine("switch (req)");
        iw.WriteLineAndIncrease("{");
        for (int i = 0; i < withResponseContracts.Count; i++)
        {
            var meta = withResponseContracts[i];
            iw.WriteLineAndIncrease($"case {meta.contractType} _contract_{i + 1}:");
            iw.WriteLine($"var _handler_{i + 1} = new {meta.handlerType}({string.Join(",", meta.servicesNames)});");
            iw.WriteLine($"var _result_{i + 1} = await _handler_{i + 1}.HandleAsync(_contract_{i + 1}, default);");
            iw.WriteLine($"return (Kanawanagasaki.BlazorContracts.ContractResult<TResponse>)(object)_result_{i + 1};");
            iw.IndentLevel--;
        }
        iw.WriteLine("default: return new Kanawanagasaki.BlazorContracts.ContractResult<TResponse>(405);");
        iw.DecreaseAndWriteLine("}");
        iw.DecreaseAndWriteLine("}");
        iw.WriteLine("catch (System.Exception e)");
        iw.WriteLineAndIncrease("{");
        iw.WriteLine("_logger.LogError(e, \"Failed to process a contract\");");
        iw.WriteLine("return new Kanawanagasaki.BlazorContracts.ContractResult<TResponse>(500, \"Internal Server Error\");");
        iw.DecreaseAndWriteLine("}");
        iw.DecreaseAndWriteLine("}");

        iw.DecreaseAndWriteLine("}");

        context.AddSource("ContractsService.g.cs", sw.ToString());
    }
}
