namespace Kanawanagasaki.BlazorContracts.SourceGenerator;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;

[Generator]
public class ContractsServiceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var config = context.AnalyzerConfigOptionsProvider.Select((options, _) =>
        {
            options.GlobalOptions.TryGetValue("build_property.BlazorContracts", out var value);
            return value;
        });

        var handlersDeclarations = context.SyntaxProvider.CreateSyntaxProvider
        (
            static (node, _) => node is ClassDeclarationSyntax classDecl && classDecl.BaseList is not null,
            static (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)ctx.Node)
        );

        var compilations = context.CompilationProvider
            .Combine(handlersDeclarations.Collect())
            .Select((tuple, _) =>
            {
                var (compilation, handlersSymbolds) = tuple;
                var ret = new List<HandlerMetadata>();

                foreach (var handler in handlersSymbolds)
                {
                    if (handler is null)
                        continue;
                    if (HandlerMetadata.TryCreate(handler, out var metadata) && metadata is not null)
                        ret.Add(metadata);
                }

                return ret.ToImmutableArray();
            });

        context.RegisterSourceOutput(config.Combine(compilations), Execute);
    }

    private void Execute(SourceProductionContext context, (string?, ImmutableArray<HandlerMetadata>) tuple)
    {
        var (config, list) = tuple;
        var optIns = config?.ToLowerInvariant().Split(',') ?? [];
        if (!optIns.Contains("serverservice"))
            return;

        var hasAuthAttributes = list.Any(m => m.EndpointAttributes.Any(a => a.IsAuthAttribute));
        var hasPolicyAuth = list.Any(m => m.EndpointAttributes.Any(a => a.IsAuthorize && a.Policy is not null));

        using var sw = new StringWriter();
        using var iw = new IndentedTextWriter(sw);
        iw.WriteLine("// <auto-generated/>");
        iw.WriteLine("#nullable enable");
        iw.WriteLine("namespace Kanawanagasaki.BlazorContracts;");

        iw.WriteLine();

        if (hasAuthAttributes)
        {
            iw.WriteLine("""
                public static class ContractsServiceExtension
                {
                    public static Microsoft.Extensions.DependencyInjection.IServiceCollection AddContracts(this Microsoft.Extensions.DependencyInjection.IServiceCollection services)
                    {
                        services.AddHttpContextAccessor();
                        services.AddScoped<Kanawanagasaki.BlazorContracts.IContractsService, ContractsService>();

                        Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.Replace(
                            services,
                            Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<
                                Microsoft.AspNetCore.Authorization.IAuthorizationMiddlewareResultHandler,
                                Kanawanagasaki.BlazorContracts.ContractAuthorizationMiddlewareResultHandler>());

                        return services;
                    }
                }
                """);
        }
        else
        {
            iw.WriteLine("""
                public static class ContractsServiceExtension
                {
                    public static Microsoft.Extensions.DependencyInjection.IServiceCollection AddContracts(this Microsoft.Extensions.DependencyInjection.IServiceCollection services)
                    {
                        services.AddHttpContextAccessor();
                        services.AddScoped<Kanawanagasaki.BlazorContracts.IContractsService, ContractsService>();
                        return services;
                    }
                }
                """);
        }

        iw.WriteLine();

        if (hasAuthAttributes)
        {
            iw.WriteLine("""
                public sealed class ContractAuthorizationMiddlewareResultHandler : Microsoft.AspNetCore.Authorization.IAuthorizationMiddlewareResultHandler
                {
                    private readonly Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler _inner = new();

                    public async System.Threading.Tasks.Task HandleAsync(
                        Microsoft.AspNetCore.Http.RequestDelegate next,
                        Microsoft.AspNetCore.Http.HttpContext context,
                        Microsoft.AspNetCore.Authorization.AuthorizationPolicy policy,
                        Microsoft.AspNetCore.Authorization.Policy.PolicyAuthorizationResult authorizeResult)
                    {
                        var isContractEndpoint =
                            context.GetEndpoint()?.Metadata.GetMetadata<Kanawanagasaki.BlazorContracts.ContractAuthEndpointMarker>() is not null;

                        if (!isContractEndpoint)
                        {
                            await _inner.HandleAsync(next, context, policy, authorizeResult);
                            return;
                        }

                        if (authorizeResult.Challenged)
                        {
                            await WriteContractResultAsync(context, Microsoft.AspNetCore.Http.StatusCodes.Status401Unauthorized, "Unauthorized");
                            return;
                        }

                        if (authorizeResult.Forbidden)
                        {
                            await WriteContractResultAsync(context, Microsoft.AspNetCore.Http.StatusCodes.Status403Forbidden, "Forbidden");
                            return;
                        }

                        await next(context);
                    }

                    private static async System.Threading.Tasks.Task WriteContractResultAsync(
                        Microsoft.AspNetCore.Http.HttpContext context, int statusCode, string errorMessage)
                    {
                        context.Response.StatusCode = statusCode;
                        context.Response.ContentType = "application/json; charset=utf-8";
                        var result = new Kanawanagasaki.BlazorContracts.ContractResult(statusCode, errorMessage);
                        await System.Text.Json.JsonSerializer.SerializeAsync(context.Response.Body, result);
                    }
                }
                """);
        }

        iw.WriteLine();

        iw.WriteLine("public class ContractsService : Kanawanagasaki.BlazorContracts.IContractsService");
        iw.WriteLineAndIncrease("{");

        iw.WriteLine("private readonly System.IServiceProvider _serviceProvider;");
        iw.WriteLine("private readonly Microsoft.Extensions.Logging.ILogger<ContractsService> _logger;");

        if (hasAuthAttributes && hasPolicyAuth)
            iw.WriteLine("private readonly Microsoft.AspNetCore.Authorization.IAuthorizationService _authorizationService;");

        iw.WriteLine();

        iw.WriteLineAndIncrease("public ContractsService(System.IServiceProvider serviceProvider)");
        iw.WriteLineAndIncrease("{");
        iw.WriteLine("_serviceProvider = serviceProvider;");
        iw.WriteLine("_logger = Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<Microsoft.Extensions.Logging.ILogger<ContractsService>>(serviceProvider);");
        if (hasAuthAttributes && hasPolicyAuth)
            iw.WriteLine("_authorizationService = Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<Microsoft.AspNetCore.Authorization.IAuthorizationService>(serviceProvider);");
        iw.DecreaseAndWriteLine("}");

        foreach (var metadata in list)
        {
            var returnTypeGenericPart = string.Empty;
            if (metadata.Contract.IsReturning)
                returnTypeGenericPart = $"<{metadata.Contract.ReturnFullyQualifiedName}>";

            iw.WriteLine();

            if (metadata.Contract.IsDisposableReturnType)
                iw.WriteLine($"public async Task<{Constants.DisposableContractResultFullName}<{metadata.Contract.ReturnFullyQualifiedName}>> ProcessAsync({metadata.Contract.FullyQualifiedName} contract, System.Threading.CancellationToken ct = default)");
            else if (metadata.Contract.IsReturning)
                iw.WriteLine($"public async Task<{Constants.ContractResultFullName}<{metadata.Contract.ReturnFullyQualifiedName}>> ProcessAsync({metadata.Contract.FullyQualifiedName} contract, System.Threading.CancellationToken ct = default)");
            else
                iw.WriteLine($"public async Task<{Constants.ContractResultFullName}> ProcessAsync({metadata.Contract.FullyQualifiedName} contract, System.Threading.CancellationToken ct = default)");
            iw.WriteLineAndIncrease("{");

            GenerateAuthorizationChecks(iw, metadata, returnTypeGenericPart);

            iw.WriteLine("try");
            iw.WriteLineAndIncrease("{");

            var constructorNames = new List<string>();
            foreach (var (injectedServiceType, _) in metadata.HandlerConstructorInjectedServicesTypes)
            {
                var fieldName = $"service{constructorNames.Count + 1}";
                iw.WriteLine($"var {fieldName} = Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{injectedServiceType}>(_serviceProvider);");
                constructorNames.Add(fieldName);
            }

            var propertyAssignments = new List<string>();
            foreach (var (injectedServiceType, propName, _, isRequired) in metadata.HandlerPropertiesInjectedServicesTypes)
            {
                var fieldName = $"service{constructorNames.Count + propertyAssignments.Count + 1}";
                if (isRequired)
                    iw.WriteLine($"var {fieldName} = Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{injectedServiceType}>(_serviceProvider);");
                else
                    iw.WriteLine($"var {fieldName} = Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService<{injectedServiceType}>(_serviceProvider);");
                propertyAssignments.Add($"{propName} = {fieldName}");
            }

            iw.Write($"var handler = new {metadata.HandlerFullyQualifiedName}({string.Join(",", constructorNames)})");
            if (0 < propertyAssignments.Count)
            {
                iw.WriteLine();
                iw.WriteLineAndIncrease("{");
                for (var i = 0; i < propertyAssignments.Count; i++)
                {
                    if (i < propertyAssignments.Count - 1)
                        iw.WriteLine($"{propertyAssignments[i]},");
                    else
                        iw.Write(propertyAssignments[i]);
                }
                iw.WriteLineAndDecrease("");
                iw.Write("}");
            }
            iw.WriteLine(";");
            iw.WriteLine("var result = await handler.HandleAsync(contract, ct);");
            if (metadata.Contract.IsDisposableReturnType)
                iw.WriteLine($"return result.AsDisposable();");
            else
                iw.WriteLine($"return result;");

            iw.DecreaseAndWriteLine("}");
            iw.WriteLine("catch (System.OperationCanceledException)");
            iw.WriteLineAndIncrease("{");
            if (metadata.Contract.IsDisposableReturnType)
                iw.WriteLine($"return new Kanawanagasaki.BlazorContracts.DisposableContractResult{returnTypeGenericPart}(499, \"Client Closed Request\");");
            else
                iw.WriteLine($"return new Kanawanagasaki.BlazorContracts.ContractResult{returnTypeGenericPart}(499, \"Client Closed Request\");");
            iw.DecreaseAndWriteLine("}");
            iw.WriteLine("catch (System.Exception e)");
            iw.WriteLineAndIncrease("{");
            iw.WriteLine("_logger.LogError(e, \"Failed to process a contract\");");
            if (metadata.Contract.IsDisposableReturnType)
                iw.WriteLine($"return new Kanawanagasaki.BlazorContracts.DisposableContractResult{returnTypeGenericPart}(500, \"Internal Server Error\");");
            else
                iw.WriteLine($"return new Kanawanagasaki.BlazorContracts.ContractResult{returnTypeGenericPart}(500, \"Internal Server Error\");");
            iw.DecreaseAndWriteLine("}");

            iw.DecreaseAndWriteLine("}");
        }

        iw.DecreaseAndWriteLine("}");

        context.AddSource("ContractsService.g.cs", sw.ToString());
    }

    private void GenerateAuthorizationChecks(IndentedTextWriter iw, HandlerMetadata metadata, string returnTypeGenericPart)
    {
        var authAttributes = metadata.EndpointAttributes.Where(a => a.IsAuthAttribute).ToList();
        if (authAttributes.Count == 0)
            return;

        if (authAttributes.Any(a => a.IsAllowAnonymous))
            return;

        var authorizeAttributes = authAttributes.Where(a => a.IsAuthorize).ToList();
        if (authorizeAttributes.Count == 0)
            return;

        var authResultIndex = 0;
        iw.WriteLine("var httpContextAccessor = Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<Microsoft.AspNetCore.Http.IHttpContextAccessor>(_serviceProvider);");
        iw.WriteLine("var user = httpContextAccessor.HttpContext?.User;");
        iw.WriteLine("if (user is null || user.Identity is null || !user.Identity.IsAuthenticated)");
        iw.WriteLineAndIncrease("{");
        if (metadata.Contract.IsDisposableReturnType)
            iw.WriteLine($"return new Kanawanagasaki.BlazorContracts.DisposableContractResult{returnTypeGenericPart}(401, \"Unauthorized\");");
        else
            iw.WriteLine($"return new Kanawanagasaki.BlazorContracts.ContractResult{returnTypeGenericPart}(401, \"Unauthorized\");");
        iw.DecreaseAndWriteLine("}");

        foreach (var authAttr in authorizeAttributes)
        {
            if (authAttr.Roles is not null)
            {
                var roles = authAttr.Roles.Split(',').Select(r => r.Trim()).Where(r => r.Length > 0).ToArray();
                if (0 < roles.Length)
                {
                    if (roles.Length == 1)
                    {
                        iw.WriteLine($"if (!user.IsInRole(\"{roles[0].Replace("\"", "\\\"")}\"))");
                    }
                    else
                    {
                        iw.Write("if (!(");
                        var roleChecks = roles.Select(r => $"user.IsInRole(\"{r.Replace("\"", "\\\"")}\")");
                        iw.Write(string.Join(" || ", roleChecks));
                        iw.WriteLine("))");
                    }
                    iw.WriteLineAndIncrease("{");
                    if (metadata.Contract.IsDisposableReturnType)
                        iw.WriteLine($"return new Kanawanagasaki.BlazorContracts.DisposableContractResult{returnTypeGenericPart}(403, \"Forbidden\");");
                    else
                        iw.WriteLine($"return new Kanawanagasaki.BlazorContracts.ContractResult{returnTypeGenericPart}(403, \"Forbidden\");");
                    iw.DecreaseAndWriteLine("}");
                }
            }

            if (authAttr.Policy is not null)
            {
                authResultIndex++;
                iw.WriteLine($"var authResult{authResultIndex} = await Microsoft.AspNetCore.Authorization.AuthorizationServiceExtensions.AuthorizeAsync(_authorizationService, user, \"{authAttr.Policy.Replace("\"", "\\\"")}\");");
                iw.WriteLine($"if (!authResult{authResultIndex}.Succeeded)");
                iw.WriteLineAndIncrease("{");
                if (metadata.Contract.IsDisposableReturnType)
                    iw.WriteLine($"return new Kanawanagasaki.BlazorContracts.DisposableContractResult{returnTypeGenericPart}(403, \"Forbidden\");");
                else
                    iw.WriteLine($"return new Kanawanagasaki.BlazorContracts.ContractResult{returnTypeGenericPart}(403, \"Forbidden\");");
                iw.DecreaseAndWriteLine("}");
            }

            if (authAttr.AuthenticationSchemes is not null)
            {
                var schemes = authAttr.AuthenticationSchemes.Split(',').Select(s => s.Trim()).Where(s => 0 < s.Length).ToArray();
                if (schemes.Length > 0)
                {
                    iw.WriteLine($"if (!user.Identities.Any(x => x.AuthenticationType is not null && new[] {{ {string.Join(", ", schemes.Select(s => $"\"{s.Replace("\"", "\\\"")}\""))} }}.Contains(identity.AuthenticationType)))");
                    iw.WriteLineAndIncrease("{");
                    if (metadata.Contract.IsDisposableReturnType)
                        iw.WriteLine($"return new Kanawanagasaki.BlazorContracts.DisposableContractResult{returnTypeGenericPart}(401, \"Unauthorized\");");
                    else
                        iw.WriteLine($"return new Kanawanagasaki.BlazorContracts.ContractResult{returnTypeGenericPart}(401, \"Unauthorized\");");
                    iw.DecreaseAndWriteLine("}");
                }
            }
        }
    }
}
