namespace Kanawanagasaki.BlazorContracts.SourceGenerator;

using Microsoft.CodeAnalysis;
using System.Collections.Immutable;

[Generator]
public class ContractsInterfaceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var config = context.AnalyzerConfigOptionsProvider.Select((options, _) =>
        {
            options.GlobalOptions.TryGetValue("build_property.BlazorContracts", out var value);
            return value;
        });

        var compilation = context.CompilationProvider.Select((compilation, ct) =>
        {
            var attributeSymb = compilation.GetTypeByMetadataName(Constants.ContractAttributeFullName);
            if (attributeSymb is null)
                return ImmutableArray<ContractMetadata>.Empty;

            var metadataList = new List<ContractMetadata>();
            foreach (var assembly in compilation.SourceModule.ReferencedAssemblySymbols.Concat([compilation.Assembly]))
            {
                if (ct.IsCancellationRequested)
                    return ImmutableArray<ContractMetadata>.Empty;

                if (Helper.IsFrameworkAssembly(assembly.ToDisplayString(Helper.SYMB_DISPLAY_FORMAT)))
                    continue;

                foreach (var type in Helper.GetAllTypes(assembly.GlobalNamespace, ct))
                {
                    if (type.GetAttributes().Any(x => SymbolEqualityComparer.Default.Equals(x.AttributeClass, attributeSymb))
                        && ContractMetadata.TryCreate(type, out var metadata)
                        && metadata is not null)
                    {
                        metadataList.Add(metadata);
                    }
                }
            }

            return metadataList.ToImmutableArray();
        });

        var combined = config.Combine(compilation);

        context.RegisterSourceOutput(combined, Execute);
    }

    private void Execute(SourceProductionContext context, (string?, ImmutableArray<ContractMetadata>) tuple)
    {
        var (config, list) = tuple;
        var optIns = config?.ToLowerInvariant().Split(',') ?? [];
        if (!optIns.Contains("interface"))
            return;

        using var sw = new StringWriter();
        using var iw = new IndentedTextWriter(sw);

        iw.WriteLine("// <auto-generated/>");
        iw.WriteLine("namespace Kanawanagasaki.BlazorContracts;");
        iw.WriteLine();
        iw.WriteLine("public interface IContractsService");
        iw.WriteLineAndIncrease("{");

        foreach (var metadata in list)
        {
            if (metadata.IsDisposableReturnType)
                iw.WriteLine($"Task<{Constants.DisposableContractResultFullName}<{metadata.ReturnFullyQualifiedName}>> ProcessAsync({metadata.FullyQualifiedName} contract, System.Threading.CancellationToken ct = default);");
            else if (metadata.IsReturning)
                iw.WriteLine($"Task<{Constants.ContractResultFullName}<{metadata.ReturnFullyQualifiedName}>> ProcessAsync({metadata.FullyQualifiedName} contract, System.Threading.CancellationToken ct = default);");
            else
                iw.WriteLine($"Task<{Constants.ContractResultFullName}> ProcessAsync({metadata.FullyQualifiedName} contract, System.Threading.CancellationToken ct = default);");
        }

        iw.DecreaseAndWriteLine("}");

        context.AddSource("IContractsService.g.cs", sw.ToString());
    }
}
