namespace Kanawanagasaki.BlazorContracts.SourceGenerator;

using Kanawanagasaki.BlazorContracts.SourceGenerator.Shared;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

[Generator]
public class ContractsExtensionsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlersDeclarations = context.SyntaxProvider.CreateSyntaxProvider
            (
                static (node, _) => node is ClassDeclarationSyntax classDecl && classDecl.BaseList is not null,
                static (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)ctx.Node)
            );

        var compilations = context.CompilationProvider
                                  .Combine(handlersDeclarations.Collect())
                                  .Select((tuple, _) =>
        {
            var (compilation, handlersSymbolds) = tuple;
            var ret = new List<HandlerMetadata>();

            foreach (var handler in handlersSymbolds)
            {
                if (handler is null)
                    continue;
                if (HandlerMetadata.TryCreate(handler, out var metadata) && metadata is not null)
                    ret.Add(metadata);
            }

            return ret;
        });

        context.RegisterSourceOutput(compilations, Execute);
    }

    private void Execute(SourceProductionContext context, List<HandlerMetadata> list)
    {
        using var sw = new StringWriter();
        using var iw = new IndentedTextWriter(sw);
        iw.WriteLine("""
                // <auto-generated/>
                namespace Kanawanagasaki.BlazorContracts;

                using Microsoft.Extensions.DependencyInjection;
                using Microsoft.AspNetCore.Builder;
                using System.Linq;

                public static class ContractsExtensions
                {
                    public static Microsoft.Extensions.DependencyInjection.IServiceCollection AddContracts(this Microsoft.Extensions.DependencyInjection.IServiceCollection __services)
                    {
                        __services.AddScoped<Kanawanagasaki.BlazorContracts.IContractsService, ContractsService>();
                        return __services;
                    }

                    public static void MapContracts(this Microsoft.AspNetCore.Routing.IEndpointRouteBuilder __endpoints)
                    {
                        var __jsonOptions = new System.Text.Json.JsonSerializerOptions
                        {
                            PropertyNamingPolicy = null,
                            DictionaryKeyPolicy = null,
                            DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull,
                            TypeInfoResolver = new System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver
                            {
                                Modifiers =
                                {
                                    __typeInfo =>
                                    {
                """);

        foreach (var item in list)
        {
            if (item.Contract.VerbStr != "Post" && item.Contract.VerbStr != "Put")
                continue;
            if (!item.Contract.Properties.Values.Any(x => x.IsByteArray || x.IsContractFile))
                continue;

            iw.IndentLevel = 6;
            iw.WriteLine($"if(__typeInfo.Type == typeof({item.Contract.FullyQualifiedName}))");
            iw.WriteLine("{");

            iw.IndentLevel++;
            foreach (var prop in item.Contract.Properties.Values)
            {
                if (prop.IsByteArray || prop.IsContractFile)
                    iw.WriteLine($"__typeInfo.Properties.Remove(__typeInfo.Properties.First(__x => __x.Name == nameof({item.Contract.FullyQualifiedName}.{prop.Name})));");
            }

            iw.DecreaseAndWriteLine("}");
        }

        iw.IndentLevel = 0;
        iw.WriteLine($$"""
                                        if(__typeInfo.Type == typeof(Kanawanagasaki.BlazorContracts.ContractResult<byte[]>))
                                        {
                                            __typeInfo.Properties.Remove(__typeInfo.Properties.First(__x => __x.Name == nameof(Kanawanagasaki.BlazorContracts.ContractResult<byte[]>.Data)));
                                        }
                                        if(__typeInfo.Type == typeof(Kanawanagasaki.BlazorContracts.ContractResult<{{typeof(Stream).FullName}}>))
                                        {
                                            __typeInfo.Properties.Remove(__typeInfo.Properties.First(__x => __x.Name == nameof(Kanawanagasaki.BlazorContracts.ContractResult<{{typeof(Stream).FullName}}>.Data)));
                                        }
                                    }
                                }
                            }
                        };
                """);

        foreach (var item in list)
        {
            iw.IndentLevel = 2;
            iw.WriteLineAndIncrease($"__endpoints.Map{item.Contract.VerbStr}(\"{item.Contract.Endpoint}\", async (");

            if (item.Contract.VerbStr == "Post" || item.Contract.VerbStr == "Put")
            {
                if (item.Contract.Properties.Values.Any(x => x.IsByteArray || x.IsContractFile))
                    iw.WriteLine("Microsoft.AspNetCore.Http.HttpRequest __httpRequest,");
                else
                    iw.WriteLine($"[Microsoft.AspNetCore.Mvc.FromBody] {item.Contract.FullyQualifiedName} __contract,");
            }

            if (item.Contract.IsByteArrayReturnType || item.Contract.IsStreamReturnType)
                iw.WriteLine("Microsoft.AspNetCore.Http.HttpResponse __httpResponse,");

            var routeParts = item.Contract.Endpoint.Split(['/', '\\'], StringSplitOptions.RemoveEmptyEntries)
                .Where(x => 2 < x.Length && x[0] == '{' && x[x.Length - 1] == '}')
                .Select(x => x.Substring(1, x.Length - 2))
                .ToArray();
            foreach (var routePart in routeParts)
                if (item.Contract.Properties.TryGetValue(routePart, out var prop))
                    iw.WriteLine($"[Microsoft.AspNetCore.Mvc.FromRoute] {prop.FullyQualifiedName} {routePart},");

            if (item.Contract.VerbStr == "Get" || item.Contract.VerbStr == "Delete")
            {
                foreach (var kv in item.Contract.Properties)
                {
                    if (0 <= routeParts.IndexOf(kv.Key))
                        continue;

                    iw.WriteLine($"[Microsoft.AspNetCore.Mvc.FromQuery] {kv.Value.FullyQualifiedName} {kv.Key},");
                }
            }

            foreach (var (injectedServiceType, injectedServiceIndex) in item.HandlerInjectedServicesTypes)
                iw.WriteLine($"{injectedServiceType} __injectedService_{injectedServiceIndex},");

            iw.WriteLine($"Microsoft.Extensions.Logging.ILogger<{item.HandlerFullyQualifiedName}> __logger,");

            iw.WriteLine("System.Threading.CancellationToken __cancellationToken) =>");
            iw.DecreaseAndWriteLine("{");
            iw.IncreaseAndWriteLine($$"""
                try
                {
                """);

            iw.IndentLevel++;

            if ((item.Contract.VerbStr == "Post" || item.Contract.VerbStr == "Put") && item.Contract.Properties.Values.Any(x => x.IsByteArray || x.IsContractFile))
            {
                iw.WriteLine($$"""
                    var __form = await __httpRequest.ReadFormAsync();

                    var __contractJson = __form["{{item.Contract.Name}}"].FirstOrDefault();
                    if (__contractJson is null)
                    {
                        var __badRequestResult = new Kanawanagasaki.BlazorContracts.ContractResult(400);
                        return Microsoft.AspNetCore.Http.Results.Json(__badRequestResult, __jsonOptions, statusCode: __badRequestResult.StatusCode);
                    }

                    {{item.Contract.FullyQualifiedName}} __contract;
                    try
                    {
                        __contract = System.Text.Json.JsonSerializer.Deserialize<{{item.Contract.FullyQualifiedName}}>(__contractJson);
                        if (__contract is null)
                        {
                            var __badRequestResult = new Kanawanagasaki.BlazorContracts.ContractResult(400);
                            return Microsoft.AspNetCore.Http.Results.Json(__badRequestResult, __jsonOptions, statusCode: __badRequestResult.StatusCode);
                        }
                    }
                    catch
                    {
                        var __badRequestResult = new Kanawanagasaki.BlazorContracts.ContractResult(400);
                        return Microsoft.AspNetCore.Http.Results.Json(__badRequestResult, __jsonOptions, statusCode: __badRequestResult.StatusCode);
                    }

                    var __toDispose = new System.Collections.Generic.List<System.IDisposable>();
                    """);

                foreach (var prop in item.Contract.Properties.Values)
                {
                    if (prop.IsByteArray)
                    {
                        iw.WriteLine($$"""
                            var __bytesFile_{{prop.Name}} = __form.Files["{{prop.Name}}"];
                            if (__bytesFile_{{prop.Name}} is not null)
                            {
                                using var __ms = new System.IO.MemoryStream();
                                await __bytesFile_{{prop.Name}}.CopyToAsync(__ms);
                                __contract.{{prop.Name}} = __ms.ToArray();
                            }
                            """);
                    }
                    else if (prop.IsContractFile)
                    {
                        iw.WriteLine($$"""
                            var __streamFile_{{prop.Name}} = __form.Files["{{prop.Name}}"];
                            if (__streamFile_{{prop.Name}} is not null)
                            {
                                var __stream = __streamFile_{{prop.Name}}.OpenReadStream();
                                __toDispose.Add(__stream);
                                __contract.{{prop.Name}} = new Kanawanagasaki.BlazorContracts.ContractFile(__stream, __streamFile_{{prop.Name}}.FileName, __streamFile_{{prop.Name}}.ContentType, __streamFile_{{prop.Name}}.Length);
                            }
                            """);
                    }
                }
            }

            if (item.Contract.VerbStr == "Get" || item.Contract.VerbStr == "Delete")
            {
                iw.WriteLine($"var __contract = new {item.Contract.FullyQualifiedName}");
                iw.WriteLine("{");
                iw.IndentLevel++;
                foreach (var propName in item.Contract.Properties.Keys)
                    iw.WriteLine($"{propName} = {propName},");
                iw.DecreaseAndWriteLine("};");
            }
            else if (0 < routeParts.Length)
            {
                foreach (var routePart in routeParts)
                    iw.WriteLine($"__contract.{routePart} = {routePart};");
            }

            var handlerConstructorArgs = string.Join(", ", item.HandlerConstructorInjectedServicesTypes.Select(x => $"__injectedService_{x.Index}"));
            iw.Write($"var __handler = new {item.HandlerFullyQualifiedName}({handlerConstructorArgs})");
            if (0 < item.HandlerPropertiesInjectedServicesTypes.Count)
            {
                iw.WriteLine();
                iw.WriteLineAndIncrease("{");
                iw.WriteLineAndDecrease(string.Join(",\n", item.HandlerPropertiesInjectedServicesTypes.Select(x => $"{x.Name} = __injectedService_{x.Index}")));
                iw.Write("}");
            }
            iw.WriteLine(";");

            iw.WriteLine($"{(item.Contract.HasResponse ? "await using " : "")}var __result = await __handler.HandleAsync(__contract, __cancellationToken);");


            if ((item.Contract.VerbStr == "Post" || item.Contract.VerbStr == "Put") && item.Contract.Properties.Values.Any(x => x.IsByteArray || x.IsContractFile))
            {
                iw.WriteLine($$"""
                    foreach (var __obj in __toDispose)
                        __obj.Dispose();
                    """);
            }

            if (item.Contract.IsByteArrayReturnType || item.Contract.IsStreamReturnType)
            {
                iw.WriteLine($$"""
                    __httpResponse.StatusCode = __result.StatusCode;
                    if (__result.StatusCode == Microsoft.AspNetCore.Http.StatusCodes.Status204NoContent)
                        return;

                    if (__result.Data is null)
                    {
                        var __json = System.Text.Json.JsonSerializer.Serialize(__result, __jsonOptions);
                        var __jsonBytes = System.Text.Encoding.UTF8.GetBytes(__json);
                        __httpResponse.ContentType = "application/json; charset=utf-8";
                        __httpResponse.ContentLength = __jsonBytes.Length;
                        await __httpResponse.Body.WriteAsync(__jsonBytes, __cancellationToken);
                    }
                    else if (__result.ErrorMessage is null)
                    {
                    """);

                if (item.Contract.IsByteArrayReturnType)
                {
                    iw.IncreaseAndWriteLine($$"""
                        __httpResponse.ContentType = "application/octet-stream";
                        __httpResponse.ContentLength = __result.Data.Length;
                        await __httpResponse.Body.WriteAsync(__result.Data, __cancellationToken);
                        """);
                }
                else
                {
                    iw.IncreaseAndWriteLine($$"""
                        __httpResponse.ContentType = "application/octet-stream";
                        if (__result.Data.CanSeek)
                        {
                            __result.Data.Position = 0;
                            __httpResponse.ContentLength = __result.Data.Length;
                        }
                        await __result.Data.CopyToAsync(__httpResponse.Body, __cancellationToken);
                        """);
                }

                iw.DecreaseAndWriteLine($$"""
                    }
                    else
                    {
                        var __boundary = "boundary" + System.Guid.NewGuid().ToString("N");
                        __httpResponse.ContentType = $"multipart/related; boundary=\"{__boundary}\"";

                        var __beforeBinary =
                            $"--{__boundary}\r\n" +
                            $"Content-Type: application/json; charset=utf-8\r\n" +
                            $"Content-Disposition: inline; name=\"{{item.Contract.Name}}\"\r\n" +
                            $"\r\n" +
                            System.Text.Json.JsonSerializer.Serialize(__result, __jsonOptions) + "\r\n" +
                            $"--{__boundary}\r\n" +
                            $"Content-Type: application/octet-stream\r\n" +
                            $"Content-Disposition: attachment; filename=\"Data.bin\"\r\n" +
                            $"Content-Transfer-Encoding: binary\r\n" +
                            $"\r\n";
                        var __beforeBinaryBytes = System.Text.Encoding.UTF8.GetBytes(__beforeBinary);
                        
                        var __afterBinary = $"\r\n--{__boundary}--\r\n";
                        var __afterBinaryBytes = System.Text.Encoding.UTF8.GetBytes(__afterBinary);

                    """);

                if (item.Contract.IsByteArrayReturnType)
                {
                    iw.IncreaseAndWriteLine($$"""
                        __httpResponse.ContentLength = __beforeBinaryBytes.Length + __result.Data.Length + __afterBinaryBytes.Length;
                        
                        await __httpResponse.Body.WriteAsync(__beforeBinaryBytes, __cancellationToken);
                        await __httpResponse.Body.WriteAsync(__result.Data, __cancellationToken);
                        await __httpResponse.Body.WriteAsync(__afterBinaryBytes, __cancellationToken);
                        """);
                }
                else
                {
                    iw.IncreaseAndWriteLine($$"""
                        if (__result.Data.CanSeek)
                        {
                            __result.Data.Position = 0;
                            __httpResponse.ContentLength = __beforeBinaryBytes.Length + __result.Data.Length + __afterBinaryBytes.Length;
                        }
                        
                        await __httpResponse.Body.WriteAsync(__beforeBinaryBytes, __cancellationToken);
                        await __result.Data.CopyToAsync(__httpResponse.Body, __cancellationToken);
                        await __httpResponse.Body.WriteAsync(__afterBinaryBytes, __cancellationToken);
                        """);
                }

                iw.DecreaseAndWriteLine("}");
            }
            else
            {
                iw.WriteLine($$"""
                    if (__result.StatusCode == Microsoft.AspNetCore.Http.StatusCodes.Status204NoContent)
                    {
                        return Microsoft.AspNetCore.Http.Results.NoContent();
                    }
                    else
                    {
                        return Microsoft.AspNetCore.Http.Results.Json(__result, __jsonOptions, statusCode: __result.StatusCode);
                    }
                    """);
            }

            iw.DecreaseAndWriteLine($$"""
                }
                catch (System.Exception e)
                {
                """);
            if (item.Contract.IsByteArrayReturnType || item.Contract.IsStreamReturnType)
            {
                iw.IncreaseAndWriteLine($$"""
                    __logger.LogError(e, "Failed to handle a contract");
                    var __internalErrorResult = new Kanawanagasaki.BlazorContracts.ContractResult(500, "Internal Server Error");
                    __httpResponse.StatusCode = __internalErrorResult.StatusCode;
                    var __json = System.Text.Json.JsonSerializer.Serialize(__internalErrorResult, __jsonOptions);
                    var __jsonBytes = System.Text.Encoding.UTF8.GetBytes(__json);
                    __httpResponse.ContentType = "application/json; charset=utf-8";
                    __httpResponse.ContentLength = __jsonBytes.Length;
                    await __httpResponse.Body.WriteAsync(__jsonBytes, __cancellationToken);
                    """);
            }
            else
            {
                iw.IncreaseAndWriteLine($$"""
                    __logger.LogError(e, "Failed to handle a contract");
                    var __internalErrorResult = new Kanawanagasaki.BlazorContracts.ContractResult(500, "Internal Server Error");
                    return Microsoft.AspNetCore.Http.Results.Json(__internalErrorResult, __jsonOptions, statusCode: __internalErrorResult.StatusCode);
                    """);
            }
            iw.DecreaseAndWriteLine("}");
            iw.DecreaseAndWriteLine("});");
        }

        iw.DecreaseAndWriteLine("}");
        iw.DecreaseAndWriteLine("}");

        context.AddSource("ContractsExtensions.g.cs", sw.ToString());
    }

    private static List<T> DeepSearchForType<T>(SyntaxNode node) where T : SyntaxNode
    {
        var res = new List<T>();

        foreach (var child in node.ChildNodes())
        {
            if (child is T t)
                res.Add(t);

            res.AddRange(DeepSearchForType<T>(child));
        }

        return res;
    }
}
