namespace Kanawanagasaki.BlazorContracts.SourceGenerator;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

[Generator]
public class ContractsExtensionsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlersDeclarations = context.SyntaxProvider.CreateSyntaxProvider
            (
                static (node, _) => node is ClassDeclarationSyntax classDecl && classDecl.BaseList is not null,
                static (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)ctx.Node)
            );

        var compilations = context.CompilationProvider
                                  .Combine(handlersDeclarations.Collect())
                                  .Select((tuple, _) =>
        {
            var (compilation, handlersSymbolds) = tuple;
            var ret = new List<HandlerTypeMetadata>();

            foreach (var handler in handlersSymbolds)
            {
                if (handler is null)
                    continue;

                var handlerInterface = handler.AllInterfaces.FirstOrDefault(
                    x => x.ContainingNamespace.ToString() + "." + x.Name == "Kanawanagasaki.BlazorContracts.IContractHandler");
                if (handlerInterface is null)
                    continue;
                if (handlerInterface.TypeArguments.Length == 0)
                    continue;

                var contractType = handlerInterface.TypeArguments[0];
                if (contractType is not INamedTypeSymbol contract)
                    continue;
                var contractInterface = contract.AllInterfaces.FirstOrDefault(
                x => x.ContainingNamespace.ToString() + "." + x.Name == "Kanawanagasaki.BlazorContracts.IContract");
                if (contractInterface is null)
                    continue;
                var contractAttribute = contract.GetAttributes().FirstOrDefault(
                    x => x.AttributeClass is not null
                      && x.AttributeClass.ContainingNamespace.ToString() + "." + x.AttributeClass.Name == "Kanawanagasaki.BlazorContracts.ContractAttribute");
                if (contractAttribute is null)
                    continue;
                if (contractAttribute.ConstructorArguments.Length != 2)
                    continue;

                var endpoint = contractAttribute.ConstructorArguments[0].Value?.ToString();
                if (endpoint is null)
                    continue;

                var verbNum = contractAttribute.ConstructorArguments[1].Value?.ToString();
                if (verbNum is null)
                    continue;

                var verbStr = verbNum switch
                {
                    "1" => "Get",
                    "2" => "Post",
                    "3" => "Put",
                    "4" => "Delete",
                    _ => null
                };

                if (verbStr is not null)
                    ret.Add(new(handler, contract, endpoint, verbStr));
            }

            return ret;
        });

        context.RegisterSourceOutput(compilations, Execute);
    }

    private void Execute(SourceProductionContext context, List<HandlerTypeMetadata> list)
    {
        using var sw = new StringWriter();
        using var iw = new IndentedTextWriter(sw);
        iw.WriteLine("""
                // <auto-generated/>
                namespace Kanawanagasaki.BlazorContracts;
                using Microsoft.Extensions.DependencyInjection;
                using Microsoft.AspNetCore.Builder;
                using System.Linq;
                public static class ContractsExtensions
                {
                    public static Microsoft.Extensions.DependencyInjection.IServiceCollection AddContracts(this Microsoft.Extensions.DependencyInjection.IServiceCollection __services)
                    {
                        __services.AddScoped<Kanawanagasaki.BlazorContracts.IContractsService, ContractsService>();
                        return __services;
                    }

                    public static void MapContracts(this Microsoft.AspNetCore.Routing.IEndpointRouteBuilder __endpoints)
                    {
                        var __jsonOptions = new System.Text.Json.JsonSerializerOptions
                        {
                            PropertyNamingPolicy = null,
                            DictionaryKeyPolicy = null,
                            DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull,
                            TypeInfoResolver = new System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver
                            {
                                Modifiers =
                                {
                                    __typeInfo =>
                                    {
                """);

        foreach (var item in list)
        {
            if (item.Verb != "Post" && item.Verb != "Put")
                continue;
            if (item.ByteArrayProps.Length == 0)
                continue;
            if (item.StreamProps.Length == 0)
                continue;

            iw.IndentLevel = 6;
            iw.WriteLine($"if(__typeInfo.Type == typeof({item.ContractFullyQualifiedName}))");
            iw.WriteLine("{");

            iw.IndentLevel++;
            foreach (var byteArrProp in item.ByteArrayProps)
                iw.WriteLine($"__typeInfo.Properties.Remove(__typeInfo.Properties.First(__x => __x.Name == nameof({item.ContractFullyQualifiedName}.{byteArrProp})));");
            foreach (var streamProp in item.StreamProps)
                iw.WriteLine($"__typeInfo.Properties.Remove(__typeInfo.Properties.First(__x => __x.Name == nameof({item.ContractFullyQualifiedName}.{streamProp})));");

            iw.DecreaseAndWriteLine("}");
        }

        iw.IndentLevel = 0;
        iw.WriteLine($$"""
                                        if(__typeInfo.Type == typeof(Kanawanagasaki.BlazorContracts.ContractResult<byte[]>))
                                        {
                                            __typeInfo.Properties.Remove(__typeInfo.Properties.First(__x => __x.Name == nameof(Kanawanagasaki.BlazorContracts.ContractResult<byte[]>.Data)));
                                        }
                                        if(__typeInfo.Type == typeof(Kanawanagasaki.BlazorContracts.ContractResult<{{typeof(Stream).FullName}}>))
                                        {
                                            __typeInfo.Properties.Remove(__typeInfo.Properties.First(__x => __x.Name == nameof(Kanawanagasaki.BlazorContracts.ContractResult<{{typeof(Stream).FullName}}>.Data)));
                                        }
                                    }
                                }
                            }
                        };
                """);

        foreach (var item in list)
        {
            iw.IndentLevel = 2;
            iw.WriteLineAndIncrease($"__endpoints.Map{item.Verb}(\"{item.Endpoint}\", async (");

            if (item.Verb == "Post" || item.Verb == "Put")
            {
                if (0 < item.ByteArrayProps.Length || 0 < item.StreamProps.Length)
                    iw.WriteLine("Microsoft.AspNetCore.Http.HttpRequest __httpRequest,");
                else
                    iw.WriteLine($"[Microsoft.AspNetCore.Mvc.FromBody] {item.ContractFullyQualifiedName} __contract,");
            }

            if (item.IsByteArrayReturnType || item.IsStreamReturnType)
                iw.WriteLine("Microsoft.AspNetCore.Http.HttpResponse __httpResponse,");

            var routeParts = item.Endpoint.Split(['/', '\\'], StringSplitOptions.RemoveEmptyEntries)
                .Where(x => 2 < x.Length && x[0] == '{' && x[x.Length - 1] == '}')
                .Select(x => x.Substring(1, x.Length - 2))
                .ToArray();
            foreach (var routePart in routeParts)
                if (item.PropNameToType.TryGetValue(routePart, out var propTypeFullname))
                    iw.WriteLine($"[Microsoft.AspNetCore.Mvc.FromRoute] {propTypeFullname} {routePart},");

            for (int i = 0; i < item.HandlerInjectedServicesTypes.Length; i++)
                iw.WriteLine($"{item.HandlerInjectedServicesTypes[i]} __injectedService_{i + 1},");

            iw.WriteLine("System.Threading.CancellationToken __cancellationToken) =>");
            iw.DecreaseAndWriteLine("{");
            iw.IncreaseAndWriteLine($$"""
                try
                {
                """);

            iw.IndentLevel++;

            if ((item.Verb == "Post" || item.Verb == "Put") && (0 < item.ByteArrayProps.Length || 0 < item.StreamProps.Length))
            {
                iw.WriteLine($$"""
                    var __form = await __httpRequest.ReadFormAsync();
                    var __contractJson = __form["{{item.ContractName}}"].FirstOrDefault();
                    if (__contractJson is null)
                    {
                        var __badRequestResult = new Kanawanagasaki.BlazorContracts.ContractResult(400);
                        return Microsoft.AspNetCore.Http.Results.Json(__badRequestResult, __jsonOptions, statusCode: __badRequestResult.StatusCode);
                    }
                    {{item.ContractFullyQualifiedName}} __contract;
                    try
                    {
                        __contract = System.Text.Json.JsonSerializer.Deserialize<{{item.ContractFullyQualifiedName}}>(__contractJson);
                        if (__contract is null)
                        {
                            var __badRequestResult = new Kanawanagasaki.BlazorContracts.ContractResult(400);
                            return Microsoft.AspNetCore.Http.Results.Json(__badRequestResult, __jsonOptions, statusCode: __badRequestResult.StatusCode);
                        }
                    }
                    catch
                    {
                        var __badRequestResult = new Kanawanagasaki.BlazorContracts.ContractResult(400);
                        return Microsoft.AspNetCore.Http.Results.Json(__badRequestResult, __jsonOptions, statusCode: __badRequestResult.StatusCode);
                    }
                    """);

                for (int i = 0; i < item.ByteArrayProps.Length; i++)
                {
                    iw.WriteLine($$"""
                        var __bytesFile_{{i + 1}} = __form.Files["{{item.ByteArrayProps[i]}}"];
                        if (__bytesFile_{{i + 1}} is not null)
                        {
                            using var __ms = new System.IO.MemoryStream();
                            await __bytesFile_{{i + 1}}.CopyToAsync(__ms);
                            __contract.{{item.ByteArrayProps[i]}} = __ms.ToArray();
                        }
                        """);
                }

                iw.WriteLine("var __toDispose = new System.Collections.Generic.List<System.IDisposable>();");
                for (int i = 0; i < item.StreamProps.Length; i++)
                {
                    iw.WriteLine($$"""
                        var __streamFile_{{i + 1}} = __form.Files["{{item.StreamProps[i]}}"];
                        if (__streamFile_{{i + 1}} is not null)
                        {
                            var __stream = __streamFile_{{i + 1}}.OpenReadStream();
                            __toDispose.Add(__stream);
                            __contract.{{item.StreamProps[i]}} = new Kanawanagasaki.BlazorContracts.ContractFile(__stream, __streamFile_{{i + 1}}.FileName, __streamFile_{{i + 1}}.ContentType, __streamFile_{{i + 1}}.Length);
                        }
                        """);
                }
            }

            if (item.Verb == "Get" || item.Verb == "Delete")
            {
                iw.WriteLine($"var __contract = new {item.ContractFullyQualifiedName}");
                iw.WriteLine("{");
                iw.IndentLevel++;
                foreach (var routePart in routeParts)
                    iw.WriteLine($"{routePart} = {routePart},");
                iw.DecreaseAndWriteLine("};");
            }
            else if (0 < routeParts.Length)
            {
                foreach (var routePart in routeParts)
                    iw.WriteLine($"__contract.{routePart} = {routePart};");
            }

            iw.WriteLine($$"""
                var __handler = new {{item.HandlerFullyQualifiedName}}({{string.Join(", ", item.HandlerInjectedServicesTypes.Select((x, i) => $"__injectedService_{i + 1}"))}});
                var __result = await __handler.HandleAsync(__contract, __cancellationToken);
                """);


            if ((item.Verb == "Post" || item.Verb == "Put") && (0 < item.ByteArrayProps.Length || 0 < item.StreamProps.Length))
            {
                iw.WriteLine($$"""
                    foreach (var __obj in __toDispose)
                        __obj.Dispose();
                    """);
            }

            if (item.IsByteArrayReturnType || item.IsStreamReturnType)
            {
                iw.WriteLine($$"""
                    __httpResponse.StatusCode = __result.StatusCode;
                    if (__result.StatusCode == Microsoft.AspNetCore.Http.StatusCodes.Status204NoContent)
                        return;

                    if (__result.Data is null)
                    {
                        var __json = System.Text.Json.JsonSerializer.Serialize(__result, __jsonOptions);
                        var __jsonBytes = System.Text.Encoding.UTF8.GetBytes(__json);
                        __httpResponse.ContentType = "application/json; charset=utf-8";
                        __httpResponse.ContentLength = __jsonBytes.Length;
                        await __httpResponse.Body.WriteAsync(__jsonBytes, __cancellationToken);
                    }
                    else if (__result.ErrorMessage is null)
                    {
                    """);

                if (item.IsByteArrayReturnType)
                {
                    iw.IncreaseAndWriteLine($$"""
                        __httpResponse.ContentType = "application/octet-stream";
                        __httpResponse.ContentLength = __result.Data.Length;
                        await __httpResponse.Body.WriteAsync(__result.Data, __cancellationToken);
                        """);
                }
                else
                {
                    iw.IncreaseAndWriteLine($$"""
                        __httpResponse.ContentType = "application/octet-stream";
                        if (__result.Data.CanSeek)
                        {
                            __result.Data.Position = 0;
                            __httpResponse.ContentLength = __result.Data.Length;
                        }
                        await __result.Data.CopyToAsync(__httpResponse.Body, __cancellationToken);
                        """);
                }

                iw.DecreaseAndWriteLine($$"""
                    }
                    else
                    {
                        var __boundary = "boundary" + System.Guid.NewGuid().ToString("N");
                        __httpResponse.ContentType = $"multipart/related; boundary=\"{__boundary}\"";

                        var __beforeBinary =
                            $"--{__boundary}\r\n" +
                            $"Content-Type: application/json; charset=utf-8\r\n" +
                            $"Content-Disposition: inline; name=\"MediaGetContract\"\r\n" +
                            $"\r\n" +
                            System.Text.Json.JsonSerializer.Serialize(__result, __jsonOptions) + "\r\n" +
                            $"--{__boundary}\r\n" +
                            $"Content-Type: application/octet-stream\r\n" +
                            $"Content-Disposition: attachment; filename=\"Data.bin\"\r\n" +
                            $"Content-Transfer-Encoding: binary\r\n" +
                            $"\r\n";
                        var __beforeBinaryBytes = System.Text.Encoding.UTF8.GetBytes(__beforeBinary);
                        
                        var __afterBinary = $"\r\n--{__boundary}--\r\n";
                        var __afterBinaryBytes = System.Text.Encoding.UTF8.GetBytes(__afterBinary);

                    """);

                if (item.IsByteArrayReturnType)
                {
                    iw.IncreaseAndWriteLine($$"""
                        __httpResponse.ContentLength = __beforeBinaryBytes.Length + __result.Data.Length + __afterBinaryBytes.Length;
                        
                        await __httpResponse.Body.WriteAsync(__beforeBinaryBytes, __cancellationToken);
                        await __httpResponse.Body.WriteAsync(__result.Data, __cancellationToken);
                        await __httpResponse.Body.WriteAsync(__afterBinaryBytes, __cancellationToken);
                        """);
                }
                else
                {
                    iw.IncreaseAndWriteLine($$"""
                        if (__result.Data.CanSeek)
                        {
                            __result.Data.Position = 0;
                            __httpResponse.ContentLength = __beforeBinaryBytes.Length + __result.Data.Length + __afterBinaryBytes.Length;
                        }
                        
                        await __httpResponse.Body.WriteAsync(__beforeBinaryBytes, __cancellationToken);
                        await __result.Data.CopyToAsync(__httpResponse.Body, __cancellationToken);
                        await __httpResponse.Body.WriteAsync(__afterBinaryBytes, __cancellationToken);
                        """);
                }

                iw.DecreaseAndWriteLine("}");
            }
            else
            {
                iw.WriteLine($$"""
                    if (__result.StatusCode == Microsoft.AspNetCore.Http.StatusCodes.Status204NoContent)
                    {
                        return Microsoft.AspNetCore.Http.Results.NoContent();
                    }
                    else
                    {
                        return Microsoft.AspNetCore.Http.Results.Json(__result, __jsonOptions, statusCode: __result.StatusCode);
                    }
                    """);
            }

            iw.DecreaseAndWriteLine($$"""
                }
                catch (System.Exception e)
                {
                """);
            if (item.IsByteArrayReturnType || item.IsStreamReturnType)
            {
                iw.IncreaseAndWriteLine($$"""
                    var __internalErrorResult = new Kanawanagasaki.BlazorContracts.ContractResult(500, e.Message);
                    __httpResponse.StatusCode = __internalErrorResult.StatusCode;
                    var __json = System.Text.Json.JsonSerializer.Serialize(__internalErrorResult, __jsonOptions);
                    var __jsonBytes = System.Text.Encoding.UTF8.GetBytes(__json);
                    __httpResponse.ContentType = "application/json; charset=utf-8";
                    __httpResponse.ContentLength = __jsonBytes.Length;
                    await __httpResponse.Body.WriteAsync(__jsonBytes, __cancellationToken);
                    """);
            }
            else
            {
                iw.IncreaseAndWriteLine($$"""
                    var __internalErrorResult = new Kanawanagasaki.BlazorContracts.ContractResult(500, e.Message);
                    return Microsoft.AspNetCore.Http.Results.Json(__internalErrorResult, __jsonOptions, statusCode: __internalErrorResult.StatusCode);
                    """);
            }
            iw.DecreaseAndWriteLine("}");
            iw.DecreaseAndWriteLine("});");
        }

        iw.DecreaseAndWriteLine("}");
        iw.DecreaseAndWriteLine("}");

        context.AddSource("ContractsExtensions.g.cs", sw.ToString());
    }

    private static List<T> DeepSearchForType<T>(SyntaxNode node) where T : SyntaxNode
    {
        var res = new List<T>();

        foreach (var child in node.ChildNodes())
        {
            if (child is T t)
                res.Add(t);

            res.AddRange(DeepSearchForType<T>(child));
        }

        return res;
    }
}
