namespace Kanawanagasaki.BlazorContracts.Client.SourceGenerator;

using Microsoft.CodeAnalysis;
using System.Text;

[Generator]
public class ClientContractsExtensionsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, Execute);
    }

    private void Execute(SourceProductionContext context, Compilation compilation)
    {
        var sb = new StringBuilder();
        sb.AppendLine("""
            // <auto-generated/>
            namespace Kanawanagasaki.BlazorContracts.Client;
            using Microsoft.Extensions.DependencyInjection;
            public static class ClientContractsExtensions
            {
                public static Microsoft.Extensions.DependencyInjection.IServiceCollection AddContracts(this Microsoft.Extensions.DependencyInjection.IServiceCollection services)
                {
                    services.AddScoped<Kanawanagasaki.BlazorContracts.IContractsService, ClientContractsService>();
                    return services;
                }
                public static Microsoft.Extensions.DependencyInjection.IServiceCollection AddContracts<T>(this Microsoft.Extensions.DependencyInjection.IServiceCollection services) where T : ClientContractsService
                {
                    services.AddScoped<Kanawanagasaki.BlazorContracts.IContractsService, T>();
                    return services;
                }
            }
            """);
        context.AddSource("ClientContractsExtensions.g.cs", sb.ToString());
    }
}
