namespace Kanawanagasaki.BlazorContracts.Client.SourceGenerator;

using Microsoft.CodeAnalysis;
using System.IO;
using System.Linq;
using Kanawanagasaki.BlazorContracts.SourceGenerator.Shared;

[Generator]
public class ClientContractsServiceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, Execute);
    }

    private void Execute(SourceProductionContext context, Compilation compilation)
    {
        var contractInterface = compilation.GetTypeByMetadataName(Constants.IContractFullName);
        var contracts = new List<ContractMetadata>();

        if (contractInterface is not null)
        {
            var types = new List<INamedTypeSymbol>();
            foreach (var assembly in compilation.SourceModule.ReferencedAssemblySymbols.Concat([compilation.Assembly]))
            {
                foreach (var type in GetAllTypes(assembly.GlobalNamespace))
                {
                    if (type.TypeKind is not TypeKind.Class)
                        continue;
                    if (type.IsAbstract)
                        continue;
                    if (!type.AllInterfaces.Contains(contractInterface))
                        continue;

                    types.Add(type);
                }
            }

            foreach (var type in types)
            {
                if (ContractMetadata.TryCreate(type, out var metadata) && metadata is not null)
                    contracts.Add(metadata);
            }
        }

        using var sw = new StringWriter();
        using var iw = new IndentedTextWriter(sw);
        iw.WriteLine("""
            // <auto-generated/>
            namespace Kanawanagasaki.BlazorContracts.Client;

            using System.Linq;

            public class ClientContractsService : Kanawanagasaki.BlazorContracts.IContractsService
            {
                private readonly System.Net.Http.HttpClient _http;
                private readonly System.Text.Json.JsonSerializerOptions _jsonOptions;

                public ClientContractsService(Microsoft.AspNetCore.Components.NavigationManager navMgr)
                {
                    this._http = new System.Net.Http.HttpClient();
                    this._http.BaseAddress = new System.Uri(navMgr.BaseUri);
                    this._jsonOptions = new System.Text.Json.JsonSerializerOptions
                    {
                        PropertyNamingPolicy = null,
                        DictionaryKeyPolicy = null,
                        DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull,
                        TypeInfoResolver = new System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver
                        {
                            Modifiers =
                            {
                                __typeInfo =>
                                {
            """);

        foreach (var contract in contracts)
        {
            if (!contract.Properties.Values.Any(x => x.IsByteArray || x.IsContractFile))
                continue;

            iw.IndentLevel = 6;
            iw.WriteLine($"if(__typeInfo.Type == typeof({contract.FullyQualifiedName}))");
            iw.WriteLine("{");

            iw.IndentLevel++;
            foreach (var prop in contract.Properties.Values)
            {
                if (prop.IsByteArray || prop.IsContractFile)
                    iw.WriteLine($"__typeInfo.Properties.Remove(__typeInfo.Properties.First(__x => __x.Name == nameof({contract.FullyQualifiedName}.{prop.Name})));");
            }

            iw.DecreaseAndWriteLine("}");
        }

        iw.IndentLevel = 0;
        iw.WriteLine($$"""
                                    if(__typeInfo.Type == typeof(Kanawanagasaki.BlazorContracts.ContractResult<byte[]>))
                                    {
                                        __typeInfo.Properties.Remove(__typeInfo.Properties.First(__x => __x.Name == nameof(Kanawanagasaki.BlazorContracts.ContractResult<byte[]>.Data)));
                                    }
                                    if(__typeInfo.Type == typeof(Kanawanagasaki.BlazorContracts.ContractResult<{{typeof(Stream).FullName}}>))
                                    {
                                        __typeInfo.Properties.Remove(__typeInfo.Properties.First(__x => __x.Name == nameof(Kanawanagasaki.BlazorContracts.ContractResult<{{typeof(Stream).FullName}}>.Data)));
                                    }
                                }
                            }
                        }
                    };
                }

                public virtual async System.Threading.Tasks.Task<Kanawanagasaki.BlazorContracts.ContractResult> ProcessAsync(Kanawanagasaki.BlazorContracts.IContract req)
                {
                    var response = await InternalProcessAsync(req);
                    Kanawanagasaki.BlazorContracts.ContractResult result;
                    if (response is null)
                        result = new Kanawanagasaki.BlazorContracts.ContractResult(405);
                    else if (response.StatusCode is System.Net.HttpStatusCode.NoContent)
                        result = new Kanawanagasaki.BlazorContracts.ContractResult((int)response.StatusCode);
                    else
                    {
                        var contentStr = await response.Content.ReadAsStringAsync();
                        result = System.Text.Json.JsonSerializer.Deserialize<Kanawanagasaki.BlazorContracts.ContractResult>(contentStr, _jsonOptions);
                    }
                    result.HttpResponse = response;
                    return result;
                }

                public virtual async System.Threading.Tasks.Task<Kanawanagasaki.BlazorContracts.ContractResult<TResponse>> ProcessAsync<TResponse>(Kanawanagasaki.BlazorContracts.IContract<TResponse> req) where TResponse : class
                {
                    var response = await InternalProcessAsync(req);
                    Kanawanagasaki.BlazorContracts.ContractResult<TResponse> result;
                    if (response is null)
                        result = new Kanawanagasaki.BlazorContracts.ContractResult<TResponse>(405);
                    else if (response.StatusCode is System.Net.HttpStatusCode.NoContent)
                        result = new Kanawanagasaki.BlazorContracts.ContractResult<TResponse>((int)response.StatusCode);
                    else
                    {
            """);

        iw.IndentLevel = 3;
        iw.WriteLine("switch (req)");
        iw.WriteLine("{");
        iw.IndentLevel++;
        foreach (var contract in contracts)
        {
            if (!contract.IsByteArrayReturnType && !contract.IsDisposableReturnType)
                continue;

            iw.WriteLine($"case {contract.FullyQualifiedName}:");
            iw.IncreaseAndWriteLine("{");

            if (contract.IsByteArrayReturnType)
            {
                iw.IncreaseAndWriteLine($$"""
                    var contentType = response.Content.Headers.ContentType?.MediaType?.ToLowerInvariant();
                    if (contentType == "application/json")
                    {
                        var contentStr = await response.Content.ReadAsStringAsync();
                        result = System.Text.Json.JsonSerializer.Deserialize<Kanawanagasaki.BlazorContracts.ContractResult<TResponse>>(contentStr, _jsonOptions);
                        break;
                    }
                    else if (contentType is not null && contentType.StartsWith("multipart/"))
                    {
                        var boundaryParam = response.Content.Headers.ContentType?.Parameters?.FirstOrDefault(p => p.Name?.Equals("boundary", System.StringComparison.OrdinalIgnoreCase) == true);
                        if (boundaryParam is null)
                        {
                            result = new Kanawanagasaki.BlazorContracts.ContractResult<TResponse>((int)response.StatusCode);
                            break;
                        }
                        var boundary = boundaryParam.Value.Trim().Trim('"');
                        if (!boundary.StartsWith("--"))
                            boundary = "--" + boundary;
                        var boundaryBytes = System.Text.Encoding.UTF8.GetBytes(boundary);
                        var crlfcrlf = System.Text.Encoding.UTF8.GetBytes("\r\n\r\n");

                        var bytes = await response.Content.ReadAsByteArrayAsync();

                        int boundaryIndexStart = 0;
                        var boundaryIndices = new System.Collections.Generic.List<int>();
                        while (true)
                        {
                            var boundaryIndex = ByteIndexOf(bytes, boundaryBytes, boundaryIndexStart);
                            if (boundaryIndex < 0)
                                break;
                            boundaryIndices.Add(boundaryIndex);
                            boundaryIndexStart = boundaryIndex + boundaryBytes.Length;
                        }

                        Kanawanagasaki.BlazorContracts.ContractResult<byte[]> byteResult = null;
                        byte[] content = null;

                        for (int i = 0; i < boundaryIndices.Count - 1; i++)
                        {
                            var startPartIndex = boundaryIndices[i] + boundaryBytes.Length;
                            var endPartIndex = boundaryIndices[i + 1];

                            if (bytes[endPartIndex - 1] == '\n')
                                endPartIndex--;
                            if (bytes[endPartIndex - 1] == '\r')
                                endPartIndex--;

                            if (endPartIndex <= startPartIndex)
                                continue;

                            var headerEndIndex = ByteIndexOf(bytes, crlfcrlf, startPartIndex);
                            if (headerEndIndex < startPartIndex || endPartIndex <= headerEndIndex)
                                continue;

                            var header = System.Text.Encoding.UTF8.GetString(bytes, startPartIndex, headerEndIndex - startPartIndex);
                            var headerDict = new System.Collections.Generic.Dictionary<string, string>(System.StringComparer.OrdinalIgnoreCase);
                            var headerLines = header.Replace("\r", "").Split('\n', System.StringSplitOptions.RemoveEmptyEntries);
                            foreach (var line in headerLines)
                            {
                                var colonIndex = line.IndexOf(':');
                                if (colonIndex <= 0)
                                    continue;
                                var name = line.Substring(0, colonIndex).Trim().ToLowerInvariant();
                                var value = line.Substring(colonIndex + 1).Trim();
                                headerDict[name] = value;
                            }

                            var contentStartIndex = headerEndIndex += crlfcrlf.Length;
                            string partContentType = null;
                            if (headerDict.TryGetValue("content-type", out var partFullContentType))
                                partContentType = partFullContentType.Split(';')[0].Trim().ToLowerInvariant();

                            if (partContentType == "application/json")
                            {
                                var json = System.Text.Encoding.UTF8.GetString(bytes, contentStartIndex, endPartIndex - contentStartIndex);
                                byteResult = System.Text.Json.JsonSerializer.Deserialize<Kanawanagasaki.BlazorContracts.ContractResult<byte[]>>(json, _jsonOptions);
                            }
                            else
                            {
                                content = new byte[endPartIndex - contentStartIndex];
                                System.Buffer.BlockCopy(bytes, contentStartIndex, content, 0, content.Length);
                            }

                            if (byteResult is not null && content is not null)
                                break;
                        }

                        if (byteResult is null && content is null)
                            result = new Kanawanagasaki.BlazorContracts.ContractResult<TResponse>((int)response.StatusCode);
                        else if (byteResult is not null)
                            result = (Kanawanagasaki.BlazorContracts.ContractResult<TResponse>)(object)byteResult;
                        else if (content is not null)
                            result = (Kanawanagasaki.BlazorContracts.ContractResult<TResponse>)(object)new Kanawanagasaki.BlazorContracts.ContractResult<byte[]>((int)response.StatusCode) { Data = content };
                        else
                        {
                            byteResult.Data = content;
                            result = (Kanawanagasaki.BlazorContracts.ContractResult<TResponse>)(object)byteResult;
                        }
                    }
                    else
                    {
                        var bytes = await response.Content.ReadAsByteArrayAsync();
                        result = (Kanawanagasaki.BlazorContracts.ContractResult<TResponse>)(object)new Kanawanagasaki.BlazorContracts.ContractResult<byte[]>
                        {
                            StatusCode = (int)response.StatusCode,
                            Data = bytes
                        };
                    }
                    """);
            }
            else if (contract.IsStreamReturnType)
            {
                iw.IncreaseAndWriteLine("var stream = await response.Content.ReadAsStreamAsync();");
                iw.WriteLine($"result = (Kanawanagasaki.BlazorContracts.ContractResult<TResponse>)(object)new Kanawanagasaki.BlazorContracts.ContractResult<{typeof(Stream).FullName}>(stream);");
            }

            iw.DecreaseAndWriteLine("}");
            iw.WriteLine("break;");
            iw.IndentLevel--;
        }
        iw.IndentLevel = 4;
        iw.WriteLine($"default:");
        iw.IncreaseAndWriteLine("{");
        iw.IncreaseAndWriteLine("var contentStr = await response.Content.ReadAsStringAsync();");
        iw.WriteLine("result = System.Text.Json.JsonSerializer.Deserialize<Kanawanagasaki.BlazorContracts.ContractResult<TResponse>>(contentStr, _jsonOptions);");
        iw.DecreaseAndWriteLine("}");
        iw.WriteLine("break;");
        iw.IndentLevel--;
        iw.DecreaseAndWriteLine("}");
        iw.DecreaseAndWriteLine("}");
        iw.IndentLevel = 0;

        iw.WriteLine("""
                    result.HttpResponse = response;
                    return result;
                }

                private async System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage> InternalProcessAsync(Kanawanagasaki.BlazorContracts.IContract req)
                {
                    System.Net.Http.HttpMethod method;
                    string endpoint;
                    System.Net.Http.HttpContent content = null;

                    switch (req)
                    {
            """);

        for (int i = 0; i < contracts.Count; i++)
        {
            var contract = contracts[i];
            var endpoint = contract.Endpoint;
            var routeParts = endpoint.Split(['/', '\\'], StringSplitOptions.RemoveEmptyEntries)
                                     .Where(x => 2 < x.Length && x[0] == '{' && x[x.Length - 1] == '}')
                                     .Select(x => x.Substring(1, x.Length - 2))
                                     .ToArray();

            foreach (var routePart in routeParts)
                endpoint = endpoint.Replace($"{{{routePart}}}", $"{{System.Web.HttpUtility.UrlEncode(_contract_{i + 1}.{routePart}.ToString())}}");

            iw.IndentLevel = 3;
            iw.WriteLine($"case {contract.FullyQualifiedName} _contract_{i + 1}:");
            iw.IncreaseAndWriteLine("{");
            iw.IndentLevel++;

            var hasQuery = false;
            if (contract.VerbStr == "Get" || contract.VerbStr == "Delete")
            {
                var query = contract.Properties.ToDictionary(x => x.Key, x => x.Value);
                foreach (var routePart in routeParts)
                    query.Remove(routePart);

                if (0 < query.Count)
                {
                    iw.WriteLine("var query = System.Web.HttpUtility.ParseQueryString(string.Empty);");
                    foreach (var kv in query)
                    {
                        if (kv.Value.IsReferenceType || kv.Value.IsNullable)
                        {
                            if (kv.Value.IsReferenceType)
                            {
                                iw.WriteLine($"if (_contract_{i + 1}.{kv.Key} is not null)");
                                iw.IncreaseAndWriteLine($"query[\"{kv.Key}\"] = _contract_{i + 1}.{kv.Key}.ToString();");
                            }
                            else
                            {
                                iw.WriteLine($"if (_contract_{i + 1}.{kv.Key}.HasValue)");
                                iw.IncreaseAndWriteLine($"query[\"{kv.Key}\"] = _contract_{i + 1}.{kv.Key}.Value.ToString();");
                            }
                            iw.IndentLevel--;
                        }
                        else
                            iw.WriteLine($"query[\"{kv.Key}\"] = _contract_{i + 1}.{kv.Key}.ToString();");
                    }
                    hasQuery = true;
                }
            }

            iw.WriteLine($$"""
                method = System.Net.Http.HttpMethod.{{contract.VerbStr}};
                endpoint = $"{{endpoint}}"{{(hasQuery ? " + \"?\" + query" : "")}};
                """);
            if (contract.VerbStr == "Post" || contract.VerbStr == "Put")
            {
                if (contract.Properties.Values.Any(x => x.IsByteArray || x.IsContractFile))
                {
                    iw.WriteLine($"""
                        var multipart = new System.Net.Http.MultipartFormDataContent();
                        var json = System.Text.Json.JsonSerializer.Serialize(_contract_{i + 1}, _jsonOptions);
                        multipart.Add(new System.Net.Http.StringContent(json, System.Text.Encoding.UTF8, "application/json"), "{contract.Name}");
                        """);

                    foreach (var prop in contract.Properties.Values)
                    {
                        if (prop.IsByteArray)
                        {
                            iw.WriteLine($$"""
                                if (_contract_{{i + 1}}.{{prop.Name}} is not null)
                                {
                                    var byteArrContent = new System.Net.Http.ByteArrayContent(_contract_{{i + 1}}.{{prop.Name}});
                                    byteArrContent.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/octet-stream");
                                    multipart.Add(byteArrContent, "{{prop.Name}}", "{{prop.Name}}.bin");
                                }
                                """);
                        }
                        else if (prop.IsContractFile)
                        {
                            iw.WriteLine($$"""
                                if (_contract_{{i + 1}}.{{prop.Name}} is not null)
                                {
                                    var streamContent = new System.Net.Http.StreamContent(_contract_{{i + 1}}.{{prop.Name}}.Stream);
                                    streamContent.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue(_contract_{{i + 1}}.{{prop.Name}}.MediaType);
                                    multipart.Add(streamContent, "{{prop.Name}}", _contract_{{i + 1}}.{{prop.Name}}.FileName);
                                }
                                """);
                        }
                    }

                    iw.WriteLine("content = multipart;");
                }
                else
                {
                    iw.WriteLine($"""
                        var json = System.Text.Json.JsonSerializer.Serialize(_contract_{i + 1}, _jsonOptions);
                        content = new System.Net.Http.StringContent(json, System.Text.Encoding.UTF8, "application/json");
                        """);
                }
            }
            iw.DecreaseAndWriteLine("""
                }
                break;
                """);
            iw.IndentLevel--;
        }

        iw.IndentLevel = 0;
        iw.WriteLine("""
            
                        default: return null;
                    }
            
                    using var request = new System.Net.Http.HttpRequestMessage(method, endpoint);
                    if (content is not null)
                        request.Content = content;
            
                    var response = await _http.SendAsync(request);

                    if (content is not null)
                        content.Dispose();

                    return response;
                }

                private static int ByteIndexOf(byte[] haystack, byte[] needle, int start)
                {
                    if (needle.Length == 0)
                        return start;
                    for (int i = start; i <= haystack.Length - needle.Length; i++)
                    {
                        var found = true;
                        for (int j = 0; j < needle.Length; j++)
                        {
                            if (haystack[i + j] != needle[j])
                            {
                                found = false;
                                break;
                            }
                        }
                        if (found)
                            return i;
                    }
                    return -1;
                }
            }
            """);

        context.AddSource("ClientContractsService.g.cs", sw.ToString());
    }

    private static IEnumerable<INamedTypeSymbol> GetAllTypes(INamespaceSymbol namespaceSymbol)
    {
        foreach (var member in namespaceSymbol.GetMembers())
        {
            if (member is INamespaceSymbol ns)
            {
                foreach (var nested in GetAllTypes(ns))
                    yield return nested;
            }
            else if (member is INamedTypeSymbol type)
            {
                yield return type;
                foreach (var t in GetAllNestedTypes(type))
                    yield return t;
            }
        }
    }

    private static IEnumerable<INamedTypeSymbol> GetAllNestedTypes(INamedTypeSymbol type)
    {
        foreach (var nested in type.GetTypeMembers())
        {
            yield return nested;
            foreach (var t in GetAllNestedTypes(nested))
                yield return t;
        }
    }
}
