namespace Kanawanagasaki.BlazorContracts.Client.SourceGenerator;

using Microsoft.CodeAnalysis;
using System.IO;
using System.Linq;

[Generator]
public class ClientContractsServiceGenerator : IIncrementalGenerator
{
    private static readonly SymbolDisplayFormat SYMB_DISPLAY_FORMAT
         = new(typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, Execute);
    }

    private void Execute(SourceProductionContext context, Compilation compilation)
    {
        var contractInterface = compilation.GetTypeByMetadataName("Kanawanagasaki.BlazorContracts.IContract");
        var contracts = new List<ContractTypeMetadata>();

        if (contractInterface is not null)
        {
            var types = new List<INamedTypeSymbol>();
            foreach (var assembly in compilation.SourceModule.ReferencedAssemblySymbols.Concat([compilation.Assembly]))
            {
                foreach (var type in GetAllTypes(assembly.GlobalNamespace))
                {
                    if (type.TypeKind is not TypeKind.Class)
                        continue;
                    if (type.IsAbstract)
                        continue;
                    if (!type.AllInterfaces.Contains(contractInterface))
                        continue;

                    types.Add(type);
                }
            }

            foreach (var type in types)
            {
                var contractAttribute = type.GetAttributes().FirstOrDefault(
                    x => x.AttributeClass is not null
                      && x.AttributeClass.ToDisplayString(SYMB_DISPLAY_FORMAT) == "Kanawanagasaki.BlazorContracts.ContractAttribute");
                if (contractAttribute is null)
                    continue;
                if (contractAttribute.ConstructorArguments.Length != 2)
                    continue;

                var endpoint = contractAttribute.ConstructorArguments[0].Value?.ToString();
                if (endpoint is null)
                    continue;

                var verbNum = contractAttribute.ConstructorArguments[1].Value?.ToString();
                if (verbNum is null)
                    continue;

                var verbStr = verbNum switch
                {
                    "1" => "Get",
                    "2" => "Post",
                    "3" => "Put",
                    "4" => "Delete",
                    _ => null
                };

                if (verbStr is not null)
                    contracts.Add(new(type, endpoint, verbStr));
            }
        }

        using var sw = new StringWriter();
        using var iw = new IndentedTextWriter(sw);
        iw.WriteLine("""
            // <auto-generated/>
            namespace Kanawanagasaki.BlazorContracts.Client;

            using System.Linq;

            public class ClientContractsService : Kanawanagasaki.BlazorContracts.IContractsService
            {
                private readonly System.Net.Http.HttpClient _http;
                private readonly System.Text.Json.JsonSerializerOptions _jsonOptions;

                public ClientContractsService(Microsoft.AspNetCore.Components.NavigationManager navMgr)
                {
                    this._http = new System.Net.Http.HttpClient();
                    this._http.BaseAddress = new System.Uri(navMgr.BaseUri);
                    _jsonOptions = new System.Text.Json.JsonSerializerOptions
                    {
                        PropertyNamingPolicy = null,
                        DictionaryKeyPolicy = null,
                        DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull,
                        TypeInfoResolver = new System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver
                        {
                            Modifiers =
                            {
                                __typeInfo =>
                                {
            """);

        foreach (var contract in contracts)
        {
            if (contract.ByteArrayProps.Length == 0 && contract.StreamProps.Length == 0)
                continue;

            iw.IndentLevel = 6;
            iw.WriteLine($"if(__typeInfo.Type == typeof({contract.FullyQualifiedName}))");
            iw.WriteLine("{");

            iw.IndentLevel++;
            foreach (var byteArrProp in contract.ByteArrayProps)
                iw.WriteLine($"__typeInfo.Properties.Remove(__typeInfo.Properties.First(__x => __x.Name == nameof({contract.FullyQualifiedName}.{byteArrProp})));");
            foreach (var streamProp in contract.StreamProps)
                iw.WriteLine($"__typeInfo.Properties.Remove(__typeInfo.Properties.First(__x => __x.Name == nameof({contract.FullyQualifiedName}.{streamProp})));");

            iw.DecreaseAndWriteLine("}");
        }

        iw.IndentLevel = 0;
        iw.WriteLine($$"""
                                    if(__typeInfo.Type == typeof(Kanawanagasaki.BlazorContracts.ContractResult<byte[]>))
                                    {
                                        __typeInfo.Properties.Remove(__typeInfo.Properties.First(__x => __x.Name == nameof(Kanawanagasaki.BlazorContracts.ContractResult<byte[]>.Data)));
                                    }
                                    if(__typeInfo.Type == typeof(Kanawanagasaki.BlazorContracts.ContractResult<{{typeof(Stream).FullName}}>))
                                    {
                                        __typeInfo.Properties.Remove(__typeInfo.Properties.First(__x => __x.Name == nameof(Kanawanagasaki.BlazorContracts.ContractResult<{{typeof(Stream).FullName}}>.Data)));
                                    }
                                }
                            }
                        }
                    };
                }

                public virtual async System.Threading.Tasks.Task<Kanawanagasaki.BlazorContracts.ContractResult> ProcessAsync(Kanawanagasaki.BlazorContracts.IContract req)
                {
                    using var response = await InternalProcessAsync(req);
                    if (response is null)
                        return new Kanawanagasaki.BlazorContracts.ContractResult(405);
                    if (response.StatusCode is System.Net.HttpStatusCode.NoContent)
                        return new Kanawanagasaki.BlazorContracts.ContractResult((int)response.StatusCode);
                    var contentStr = await response.Content.ReadAsStringAsync();
                    return System.Text.Json.JsonSerializer.Deserialize<Kanawanagasaki.BlazorContracts.ContractResult>(contentStr, _jsonOptions);
                }

                public virtual async System.Threading.Tasks.Task<Kanawanagasaki.BlazorContracts.ContractResult<TResponse>> ProcessAsync<TResponse>(Kanawanagasaki.BlazorContracts.IContract<TResponse> req) where TResponse : class
                {
                    using var response = await InternalProcessAsync(req);
                    if (response is null)
                        return new Kanawanagasaki.BlazorContracts.ContractResult<TResponse>(405);
                    if (response.StatusCode is System.Net.HttpStatusCode.NoContent)
                        return new Kanawanagasaki.BlazorContracts.ContractResult<TResponse>((int)response.StatusCode);
            """);

        iw.IndentLevel = 2;
        iw.WriteLine("switch (req)");
        iw.WriteLine("{");
        iw.IndentLevel++;
        foreach (var contract in contracts)
        {
            if (!contract.IsByteArrayReturnType && !contract.IsStreamReturnType)
                continue;

            iw.WriteLine($"case {contract.FullyQualifiedName}:");
            iw.IncreaseAndWriteLine("{");

            if (contract.IsByteArrayReturnType)
            {
                iw.IncreaseAndWriteLine($$"""
                    var contentType = response.Content.Headers.ContentType?.MediaType?.ToLowerInvariant();
                    if (contentType == "application/json")
                    {
                        var contentStr = await response.Content.ReadAsStringAsync();
                        return System.Text.Json.JsonSerializer.Deserialize<Kanawanagasaki.BlazorContracts.ContractResult<TResponse>>(contentStr, _jsonOptions);
                    }
                    else if (contentType is not null && contentType.StartsWith("multipart/"))
                    {
                        var boundaryParam = response.Content.Headers.ContentType?.Parameters?.FirstOrDefault(p => p.Name?.Equals("boundary", System.StringComparison.OrdinalIgnoreCase) == true);
                        if (boundaryParam is null)
                            return new Kanawanagasaki.BlazorContracts.ContractResult<TResponse>((int)response.StatusCode);
                        var boundary = boundaryParam.Value.Trim().Trim('"');
                        if (!boundary.StartsWith("--"))
                            boundary = "--" + boundary;
                        var boundaryBytes = System.Text.Encoding.UTF8.GetBytes(boundary);
                        var crlfcrlf = System.Text.Encoding.UTF8.GetBytes("\r\n\r\n");

                        var bytes = await response.Content.ReadAsByteArrayAsync();

                        int boundaryIndexStart = 0;
                        var boundaryIndices = new System.Collections.Generic.List<int>();
                        while (true)
                        {
                            var boundaryIndex = ByteIndexOf(bytes, boundaryBytes, boundaryIndexStart);
                            if (boundaryIndex < 0)
                                break;
                            boundaryIndices.Add(boundaryIndex);
                            boundaryIndexStart = boundaryIndex + boundaryBytes.Length;
                        }

                        Kanawanagasaki.BlazorContracts.ContractResult<byte[]> result = null;
                        byte[] content = null;

                        for (int i = 0; i < boundaryIndices.Count - 1; i++)
                        {
                            var startPartIndex = boundaryIndices[i] + boundaryBytes.Length;
                            var endPartIndex = boundaryIndices[i + 1];

                            if (bytes[endPartIndex - 1] == '\n')
                                endPartIndex--;
                            if (bytes[endPartIndex - 1] == '\r')
                                endPartIndex--;

                            if (endPartIndex <= startPartIndex)
                                continue;

                            var headerEndIndex = ByteIndexOf(bytes, crlfcrlf, startPartIndex);
                            if (headerEndIndex < startPartIndex || endPartIndex <= headerEndIndex)
                                continue;

                            var header = System.Text.Encoding.UTF8.GetString(bytes, startPartIndex, headerEndIndex - startPartIndex);
                            var headerDict = new System.Collections.Generic.Dictionary<string, string>(System.StringComparer.OrdinalIgnoreCase);
                            var headerLines = header.Replace("\r", "").Split('\n', System.StringSplitOptions.RemoveEmptyEntries);
                            foreach (var line in headerLines)
                            {
                                var colonIndex = line.IndexOf(':');
                                if (colonIndex <= 0)
                                    continue;
                                var name = line.Substring(0, colonIndex).Trim().ToLowerInvariant();
                                var value = line.Substring(colonIndex + 1).Trim();
                                headerDict[name] = value;
                            }

                            var contentStartIndex = headerEndIndex += crlfcrlf.Length;
                            string partContentType = null;
                            if (headerDict.TryGetValue("content-type", out var partFullContentType))
                                partContentType = partFullContentType.Split(';')[0].Trim().ToLowerInvariant();

                            if (partContentType == "application/json")
                            {
                                var json = System.Text.Encoding.UTF8.GetString(bytes, contentStartIndex, endPartIndex - contentStartIndex);
                                result = System.Text.Json.JsonSerializer.Deserialize<Kanawanagasaki.BlazorContracts.ContractResult<byte[]>>(json, _jsonOptions);
                            }
                            else
                            {
                                content = new byte[endPartIndex - contentStartIndex];
                                System.Buffer.BlockCopy(bytes, contentStartIndex, content, 0, content.Length);
                            }

                            if (result is not null && content is not null)
                                break;
                        }

                        if (result is null && content is null)
                            return new Kanawanagasaki.BlazorContracts.ContractResult<TResponse>((int)response.StatusCode);
                        else if (content is null)
                            return (Kanawanagasaki.BlazorContracts.ContractResult<TResponse>)(object)result;
                        else if (result is null)
                            return (Kanawanagasaki.BlazorContracts.ContractResult<TResponse>)(object)new Kanawanagasaki.BlazorContracts.ContractResult<byte[]>((int)response.StatusCode) { Data = content };
                        else
                        {
                            result.Data = content;
                            return (Kanawanagasaki.BlazorContracts.ContractResult<TResponse>)(object)result;
                        }
                    }
                    else
                    {
                        var bytes = await response.Content.ReadAsByteArrayAsync();
                        return (Kanawanagasaki.BlazorContracts.ContractResult<TResponse>)(object)new Kanawanagasaki.BlazorContracts.ContractResult<byte[]>
                        {
                            StatusCode = (int)response.StatusCode,
                            Data = bytes
                        };
                    }
                    """);
            }
            else if (contract.IsStreamReturnType)
            {
                iw.IncreaseAndWriteLine("var stream = await response.Content.ReadAsStreamAsync();");
                iw.WriteLine($"return (Kanawanagasaki.BlazorContracts.ContractResult<TResponse>)(object)new Kanawanagasaki.BlazorContracts.ContractResult<{typeof(Stream).FullName}>(stream);");
            }

            iw.DecreaseAndWriteLine("}");
            iw.IndentLevel--;
        }
        iw.IndentLevel = 3;
        iw.WriteLine($"default:");
        iw.IncreaseAndWriteLine("{");
        iw.IncreaseAndWriteLine("var contentStr = await response.Content.ReadAsStringAsync();");
        iw.WriteLine("return System.Text.Json.JsonSerializer.Deserialize<Kanawanagasaki.BlazorContracts.ContractResult<TResponse>>(contentStr, _jsonOptions);");
        iw.DecreaseAndWriteLine("}");
        iw.IndentLevel--;
        iw.DecreaseAndWriteLine("}");
        iw.IndentLevel = 0;

        iw.WriteLine("""
                }

                private async System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage> InternalProcessAsync(Kanawanagasaki.BlazorContracts.IContract req)
                {
                    System.Net.Http.HttpMethod method;
                    string endpoint;
                    System.Net.Http.HttpContent content = null;

                    switch (req)
                    {
            """);

        for (int i = 0; i < contracts.Count; i++)
        {
            var contract = contracts[i];

            var endpoint = contract.Endpoint;
            var routeParts = contract.Endpoint.Split(['/', '\\'], StringSplitOptions.RemoveEmptyEntries)
                                              .Where(x => 2 < x.Length && x[0] == '{' && x[x.Length - 1] == '}')
                                              .Select(x => x.Substring(1, x.Length - 2))
                                              .ToArray();

            foreach (var routePart in routeParts)
                endpoint = endpoint.Replace($"{{{routePart}}}", $"{{System.Web.HttpUtility.UrlEncode(_contract_{i + 1}.{routePart}.ToString())}}");

            iw.IndentLevel = 3;
            iw.WriteLine($"case {contract.FullyQualifiedName} _contract_{i + 1}:");
            iw.IncreaseAndWriteLine($$"""
                {
                    method = System.Net.Http.HttpMethod.{{contract.Verb}};
                    endpoint = $"{{endpoint}}";
                """);
            if (contract.Verb == "Post" || contract.Verb == "Put")
            {
                if (0 < contract.ByteArrayProps.Length || 0 < contract.StreamProps.Length)
                {
                    iw.IncreaseAndWriteLine($"""
                        var multipart = new System.Net.Http.MultipartFormDataContent();
                        var json = System.Text.Json.JsonSerializer.Serialize(_contract_{i + 1}, _jsonOptions);
                        multipart.Add(new System.Net.Http.StringContent(json, System.Text.Encoding.UTF8, "application/json"), "{contract.Name}");
                        """);

                    foreach (var byteArrProp in contract.ByteArrayProps)
                    {
                        iw.WriteLine($$"""
                            if (_contract_{{i + 1}}.{{byteArrProp}} is not null)
                            {
                                var byteArrContent = new System.Net.Http.ByteArrayContent(_contract_{{i + 1}}.{{byteArrProp}});
                                byteArrContent.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/octet-stream");
                                multipart.Add(byteArrContent, "{{byteArrProp}}", "{{byteArrProp}}.bin");
                            }
                            """);
                    }

                    foreach (var streamProp in contract.StreamProps)
                    {
                        iw.WriteLine($$"""
                            if (_contract_{{i + 1}}.{{streamProp}} is not null)
                            {
                                var streamContent = new System.Net.Http.StreamContent(_contract_{{i + 1}}.{{streamProp}}.Stream);
                                streamContent.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue(_contract_{{i + 1}}.{{streamProp}}.MediaType);
                                multipart.Add(streamContent, "{{streamProp}}", _contract_{{i + 1}}.{{streamProp}}.FileName);
                            }
                            """);
                    }

                    iw.WriteLine("content = multipart;");
                }
                else
                {
                    iw.IncreaseAndWriteLine($"""
                        var json = System.Text.Json.JsonSerializer.Serialize(_contract_{i + 1}, _jsonOptions);
                        content = new System.Net.Http.StringContent(json, System.Text.Encoding.UTF8, "application/json");
                        """);
                }

                iw.IndentLevel--;
            }
            iw.WriteLine("""
                }
                break;
                """);
            iw.IndentLevel--;
        }

        iw.IndentLevel = 0;
        iw.WriteLine("""
            
                        default: return null;
                    }
            
                    using var request = new System.Net.Http.HttpRequestMessage(method, endpoint);
                    if (content is not null)
                        request.Content = content;
            
                    var response = await _http.SendAsync(request);

                    if (content is not null)
                        content.Dispose();

                    return response;
                }

                private static int ByteIndexOf(byte[] haystack, byte[] needle, int start)
                {
                    if (needle.Length == 0)
                        return start;
                    for (int i = start; i <= haystack.Length - needle.Length; i++)
                    {
                        var found = true;
                        for (int j = 0; j < needle.Length; j++)
                        {
                            if (haystack[i + j] != needle[j])
                            {
                                found = false;
                                break;
                            }
                        }
                        if (found)
                            return i;
                    }
                    return -1;
                }
            }
            """);

        context.AddSource("ClientContractsService.g.cs", sw.ToString());
    }

    private static IEnumerable<INamedTypeSymbol> GetAllTypes(INamespaceSymbol namespaceSymbol)
    {
        foreach (var member in namespaceSymbol.GetMembers())
        {
            if (member is INamespaceSymbol ns)
            {
                foreach (var nested in GetAllTypes(ns))
                    yield return nested;
            }
            else if (member is INamedTypeSymbol type)
            {
                yield return type;
                foreach (var t in GetAllNestedTypes(type))
                    yield return t;
            }
        }
    }

    private static IEnumerable<INamedTypeSymbol> GetAllNestedTypes(INamedTypeSymbol type)
    {
        foreach (var nested in type.GetTypeMembers())
        {
            yield return nested;
            foreach (var t in GetAllNestedTypes(nested))
                yield return t;
        }
    }
}
