<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<BlazorContracts>Interface</BlazorContracts>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Kanawanagasaki.BlazorContracts\Kanawanagasaki.BlazorContracts.csproj" />
	</ItemGroup>

	<ItemGroup>
		<CompilerVisibleProperty Include="BlazorContracts" />
		<ProjectReference Include="..\Kanawanagasaki.BlazorContracts.SourceGenerator\Kanawanagasaki.BlazorContracts.SourceGenerator.csproj"
						  OutputItemType="Analyzer"
						  ReferenceOutputAssembly="false" />
	</ItemGroup>

</Project>
